### ISSUE TITLE
SAN switches with 8.0.2b are not pining from Ansible

### ISSUE THREAD

**Issue by SRINIVASANNAVARAPU** [brocade/ansible#1]
All,
I am want to use brocade new feature with ansible, when I am initially tying to ping the switch using ansible. I am getting below output.
"msg": "failed to resolve remote temporary directory from ansible-tmp-1531129086.14-166582234734344: `( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1531129086.14-166582234734344 `\" && echo ansible-tmp-1531129086.14-166582234734344=\"` echo ~/.ansible/tmp/ansible-tmp-1531129086.14-166582234734344 `\" )` returned empty string"

**Comment by brianwells** [comment]
FWIW, I'm currently using `v8.2.0b` and ping works fine.

**Comment by SRINIVASANNAVARAPU** [comment]
This is working for me also
