### ISSUE TITLE
Brocade gather facts module failure

### ISSUE THREAD

**Issue by mahlac** [brocade/ansible#102]
Module name - brocade_facts

Getting below error while gathering broacade facts
#######################################################################################################
{
    "msg": "Unexpected failure during module execution.",
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/executor/task_executor.py\", line 147, in run\n    res = self._execute()\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/executor/task_executor.py\", line 665, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/plugins/action/normal.py\", line 46, in run\n    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/plugins/action/__init__.py\", line 825, in _execute_module\n    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/plugins/action/__init__.py\", line 211, in _configure_module\n    **become_kwargs)\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/executor/module_common.py\", line 1253, in modify_module\n    environment=environment)\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/executor/module_common.py\", line 1090, in _find_module_utils\n    py_module_cache, zf)\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/executor/module_common.py\", line 726, in recursive_finder\n    [os.path.join(*py_module_name[:-idx])])\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/executor/module_common.py\", line 645, in __init__\n    self.get_source()\n  File \"/var/lib/awx/venv/py3/lib/python3.6/site-packages/ansible/executor/module_common.py\", line 661, in get_source\n    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))\n  File \"/usr/lib64/python3.6/pkgutil.py\", line 616, in get_data\n    spec = importlib.util.find_spec(package)\n  File \"/usr/lib64/python3.6/importlib/util.py\", line 102, in find_spec\n    raise ValueError('{}.__spec__ is None'.format(name))\nValueError: ansible_collections.brocade.fos.plugins.module_utils.brocade_objects.__spec__ is None\n",
    "stdout": "",
    "_ansible_no_log": false
}
#######################################################################################################

**Comment by pv890448** [comment]
Which command is run to gather facts? Could you please let us know command that is run? What is the version of Ansible, python and openssl?

**Comment by prasad-valmeti-broadcom** [comment]
Could you please provide information that is requested here?
Which command is run to gather facts? Could you please let us know command that is run? What is the version of Ansible, python and openssl?

**Comment by mahlac** [comment]
Issue resolved after installing pyfos library.
It was not mentioned in ansible documentation as required. But to work pyfos library is needed.

**Comment by mahlac** [comment]
Resolved
