### ISSUE TITLE
Invalid REST URI

### ISSUE THREAD

**Issue by amrit-chhetri** [brocade/ansible#108]
Hi Team,

While using the ansible latest module(1.3.0 ) located in https://galaxy.ansible.com/brocade/fos and https://github.com/brocade/ansible we are getting an Invalid “Invalid REST URI” error.

The same ansible script works fine in 9.0.1 but post switch firmware update from 9.0.1b -> 9.1.0b we are seeing the below issue.
Hence please guide.

FYI:
GET_resp_code: 400
  GET_resp_data:
    errors:
      '@xmlns': urn:ietf:params:xml:ns:yang:ietf-restconf
      error:
        error-app-tag: Error
        error-info:
          error-code: '5'
          error-module: rest
        error-message: Invalid REST URI
        error-tag: unknown-element
        error-type: application
  GET_resp_reason: Bad Request
  GET_url: [http://********/rest/running/zoning/effective-configuration](http://%2A%2A%2A%2A%2A%2A%2A%2A/rest/running/zoning/effective-configuration)
  POST_url: [http://********/rest/logout](http://%2A%2A%2A%2A%2A%2A%2A%2A/rest/logout)
  ansible_loop_var: item
  invocation:
    module_args:
      aliases:
      - members:
        - xx:xx:xx:xx:xx:xx:xx:xx
        name: T_hec01stor01_p_0_3_1
      aliases_to_delete: null
      credential:
        fos_ip_addr: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        fos_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        fos_user_name: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        https: false
      members_add_only: null
      members_remove_only: null
      throttle: null
      timeout: null
      vfid: -1
  item:
    source: p_0_3_1
    wwid: xx:xx:xx:xx:xx:xx:xx:xx
  msg: failed to checksum

Regards
Amrit Chhetri

**Comment by BGmot** [comment]
Take a look at https://github.com/brocade/ansible/issues/101

**Comment by prasad-valmeti-broadcom** [comment]
This is just to give an update on this issue. Currently issue is addressed, and release test is in progress.  Once test is finished in few weeks, will merge changes into galaxy branch.

**Comment by prasad-valmeti-broadcom** [comment]
Ansible fos 1.3.1 is posted to galaxy collections in Apr 2023. Please try with the latest ansible and let us know if the issue is still there.

**Comment by prasad-valmeti-broadcom** [comment]
If there are no further issues, please suggest if we can close the issue.

**Comment by amrit-chhetri** [comment]
We are yet to test the new fos 1.3.1. 
But we can close this issue for now.
