### ISSUE TITLE
Wrong behavior when uppercase WWNs are in alias

### ISSUE THREAD

**Issue by Piaskun** [brocade/ansible#11]
Hello,
Looks like WWNs in members list should be changed to lowercase before REST API call is made.
Switches keep all WWN in lowercase in database, so when you add WWN with uppercase A-F to members list, and run 'brocade_zoning_alias' task, it will first compare WWNs from members list with WWNs in switch, but since there is case difference, it will not detect, that all members are the same, and will try push REST call to modify alias.

Then you get:
fatal: [host]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "HTTP POST failed", "post_resp_code": 400, "post_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "-8", "error-module": "zone"}, "error-message": "Error: \"Host_1\" create failed due to duplicate name and content.", "error-path": "/alias/alias-name/Host_1/", "error-tag": "Operation-failed", "error-type": "protocol"}}}, "post_resp_reason": "Bad Request", "post_url": "http://<ip>/rest/running/zoning/defined-configuration?vf-id=128"}

How to test:
In zoning_zone.yml example, modify one WWN to have uppercase A-F inside (ie. change 11:22:33:44:55:66:77:88 to 11:22:33:44:55:66:77:AA)
Run playbook twice - first will create alises (but they will be in database with lowercase in WWN), second will fail (module will not detect, that no changes are needed).

PS. Thanks for all the work!

**Comment by daniel-chung-broadcom** [comment]
Thanks for the input. I'll keep you posted on the defect.

**Comment by daniel-chung-broadcom** [comment]
merged the fix into the master branch. Please check it out and let me know if additional issues.

fyi. I also updated file paths and use of ansible.cfg to point to module_utils directory. 

Thanks.
