### ISSUE TITLE
Publish latest changes to Galaxy

### ISSUE THREAD

**Issue by pint2oo** [brocade/ansible#118]
Hi, 

The latest version of the brocade.fos collection on Ansible Galaxy dates back a year ago : https://galaxy.ansible.com/brocade/fos

Could the latest modifications (like the latest commits related to URI changes) be published ?

Thank you for your work,

pint2oo

**Comment by rzfeeser** [comment]
If you want to install the collection from the branch with the latest commits, I think that is the "galaxy" branch... you could do that with the following command (i.e. you don't need to use galaxy.ansible.com to install your collections, just install straight from the repository)

```
ansible-galaxy collection install git+https://github.com/brocade/ansible/,galaxy
```

**Comment by prasad-valmeti-broadcom** [comment]
Updated latest galaxy collection to ansible 1.3.1 in April 2023. Hope this helps for your purpose.

**Comment by prasad-valmeti-broadcom** [comment]
Please let us know if we close the issue.

**Comment by prasad-valmeti-broadcom** [comment]
Please let us know if we can close the issue.
