### ISSUE TITLE
Add module for configuring REST parameters

### ISSUE THREAD

**Issue by mgoetze5** [brocade/ansible#119]
I'd like to have a module that can do the equivalent of the following CLI commands:

```
mgmtapp --config -samplerequest 500 -maxrestsession 10
mgmtapp --enable keepalive
```

I couldn't find a module to do this in the REST API reference so this would presumably have to be accomplished via SSH.

**Comment by prasad-valmeti-broadcom** [comment]
This can be done with the brocade_single_obj, please refer to the documentation for how to do it for generic modules.
If this doesn't suffice your purpose, please let us know the specific reason why it needs a separate module.

**Comment by mgoetze5** [comment]
As I stated in the initial report, I couldn't find a way to do this in the REST API reference, so I don't see how brocade_single_obj can accomplish it.

**Comment by prasad-valmeti-broadcom** [comment]
REST API support is provided for mgmtapp CLI in the latest releases, it is available from 9. x releases.
What is the version of FOS that is used? I can check and confirm.

**Comment by prasad-valmeti-broadcom** [comment]
Could you please let us know the status of this issue? If the issue is resolved, please let us know if we can close the issue.

**Comment by mgoetze5** [comment]
We are still on FOS 8.2.x as we still have a lot of Gen5 hardware, so it doesn't really help me that it's in FOS 9.x, but I understand if you don't want to spend time on this.

**Comment by prasad-valmeti-broadcom** [comment]
Currently, there is no plan to backport mgmtapp REST support to 8.2.x releases.
If there are no further issues, please suggest if we can close this issue.

**Comment by mgoetze5** [comment]
I've moved on to a different employer where we will soon be mostly on FOS 9.x, so as far as I'm concerned you can close this.
