### ISSUE TITLE
Insecure usage of SSH client

### ISSUE THREAD

**Issue by ttuellmann** [brocade/ansible#13]
The code leveraging SSH, where information is not available via REST, is vulnerable to man-in-the-middle-attacks.

The way `ssh_and_configure` is called in the code, the missing host key policy is always set to `paramiko.client.WarningPolicy()`. This setting even allows connections to hosts presenting a host key different from the one stored in `~/.ssh/known_hosts`. This basically disables the SSH trust model and leaves the client open to man-in-the-middle attacks compromising the FOS credentials. 

Normally, Paramiko would at least print a warning message, but because of the way it is used from within Ansible, the warning message is not displayed when running a playbook.

You could make the `hostkeymust` configurable from playbooks and default to `True` wherever `ssh_and_configure` is called. Having everything available through REST would of course the preferable approach.

**Comment by daniel-chung-broadcom** [comment]
Thanks for the info.

**Comment by daniel-chung-broadcom** [comment]
pulled changes to change the default to true. and provide an optional attribute in the playbook.
