### ISSUE TITLE
Way for configure esrsconfig in FOS

### ISSUE THREAD

**Issue by diazj1** [brocade/ansible#131]
Hi guys:

Are there any way to configure esrsconfig using this ansible module?
I can't find it.

Thanks and regards
JC

**Comment by prasad-valmeti-broadcom** [comment]
Currently there is no REST support for the ESRS config. Since Ansible uses REST, so there is no support of it. In case, if it needs to be supported an MRD requirement need to create for PM to consider for future releases.

**Comment by prasad-valmeti-broadcom** [comment]
If there are no further issues, please suggest if we can close this issue.

**Comment by diazj1** [comment]
Yes pleae, close it.
