### ISSUE TITLE
brocade_zoning_cfg.py does not log cfgsave, cfgenable in errdump 

### ISSUE THREAD

**Issue by demonoid666** [brocade/ansible#14]
It is found brocade_zoning_cfg function does not log any information related to cfgsave and cfgenable in switch log. Errdump does not show any related log eg. ZONE-1022 & ZONE-1024

**Comment by daniel-chung-broadcom** [comment]
are you able to share specific steps that I can try to repro the scenario?

**Comment by demonoid666** [comment]
Hardware
    SAN Switch: Brocade 6520
    FOS            : v8.2.1c
Ansible 
    Host: RHEL 7.4
    Python: v3.6.8
    Ansible: v2.7.5
    Brocade ansible version: Nov 2019 (latest)

The playbook completed successfully and it is found the cfg updated and enabled on the target SAN switch. However, sometimes we are not able to see the following in errdump

"cfgSave completes successfully."
"The effective configuration has changed to XXXXXX"

The step to reproduce the case (no cfgsave in errdump): 
# Clean UP 
1. ssh Login to the SAN switch 
2. execute CLI cfgdisable
3. execute CLI cfgclear
4. execute CLI cfgsave
5. Create dummy alias, zoning and cfg 
    $ alicreate "dummy1", "11:22:33:44:55:66:77:00"
    $ alicreate "dummy2", "11:22:33:44:55:66:77:01" 
    $ zonecreate "Zdummy1_dummy2","dummy1;dummy2"
    $ cfgcreate "DC_CFG","Zdummy1_dummy2"
    $ cfgsave -f
6. logout ssh session
7. login ssh session again (to create a SEC-1203 event in errdump)
8. from ansible host run the ansible playbook to add alias, zoning, update and enable configuration 
9. ssh to SAN switch and there is no cfgsave (ZONE-1024) found in errdump

Possible cfgsave or cfgenable playbook/CLI were executed in very short time and triggered LOG-1000 event?

**Comment by demonoid666** [comment]
Hardware
    SAN Switch: Brocade 6520
    FOS            : v8.2.1c
Ansible 
    Host: RHEL 7.4
    Python: v3.6.8
    Ansible: v2.7.5
    Brocade ansible version: Nov 2019 (latest)

The playbook completed successfully and it is found the cfg updated and enabled on the target SAN switch. However, sometimes we are not able to see the following in errdump

"cfgSave completes successfully."
"The effective configuration has changed to XXXXXX"

The step to reproduce the case (no cfgsave in errdump): 
 
1. ssh Login to the SAN switch 
2. Clean up Zoning configuration 
    $ cfgdisable -f 
    $ cfgclear
    $ cfgsave -f 
3. Create dummy alias, zoning and cfg 
    $ alicreate "dummy1", "11:22:33:44:55:66:77:00"
    $ alicreate "dummy2", "11:22:33:44:55:66:77:01" 
    $ zonecreate "Zdummy1_dummy2","dummy1;dummy2"
    $ cfgcreate "DC_CFG","Zdummy1_dummy2"
    $ cfgsave -f
4. logout ssh session
5. login ssh session again (To create a SEC-1203 event in errdump) 
6. from ansible host run the ansible playbook to add alias, zoning, update and enable configuration 
7. ssh to SAN switch and there is no cfgsave (ZONE-1024) found in errdump

Possible execute cfgsave/cfgenable too frequent and triggered event "LOG-1000" and the related logs is suppressed?

**Comment by daniel-chung-broadcom** [comment]
I followed the process detailed above. I see that on my console connection, I see the following when I execute the zoning_zone.yml playbook in the task directory.

sw0:FID128:admin> sw0 Updating flash ...
2020/01/07-17:42:59, [ZONE-1024], 110, FID 128, INFO, sw0, cfgSave completes successfully.
sw0 Updating flash ...
sw0 Updating flash ...
2020/01/07-17:43:19, [LOG-1000], 111, FID 128, INFO, sw0, Previous message repeated 1 time(s).
2020/01/07-17:43:19, [ZONE-1022], 112, FID 128, INFO, sw0, The effective configuration has changed to newcfg2.   

errdump content shows me the following.

2020/01/07-17:42:59, [ZONE-1024], 110, FID 128, INFO, sw0, cfgSave completes successfully.

2020/01/07-17:43:19, [LOG-1000], 111, FID 128, INFO, sw0, Previous message repeated 1 time(s).

2020/01/07-17:43:19, [ZONE-1022], 112, FID 128, INFO, sw0, The effective configuration has changed to newcfg2.   

sw0:FID128:admin> date
Tue Jan  7 17:45:30 UTC 2020
sw0:FID128:admin> 

I do see some log-1000 messages for duplicate logs but I still do see the original cfgsave as well as cfgenable action.

**Comment by demonoid666** [comment]
Thanks for you reply. 

In my test, if the playbook being executed multiple time in short time(eg. 5~10 min) the cfgsave message will be suppressed by LOG-1000 event in errdump.

**Comment by daniel-chung-broadcom** [comment]
if you are generating back to back cfgsave messages, I believe the dup message is expected behavior. if you are executing the same play over and over, I expect that there will not be any messages since there will be no changes due to the ansible zoning module identifying the existing zoning db as matching to the desired db content. As far as I can tell, the overall behavior described seems to follow the expected FOS behavior. Please let me know if you feel otherwise.

**Comment by demonoid666** [comment]
Agreed, it shall be an expected FOS behavior. Please close the case.

Thanks for your time.
