### ISSUE TITLE
How to create a new virtualswitch?

### ISSUE THREAD

**Issue by diazj1** [brocade/ansible#141]
Hi guys.

Are there any way for create a new vfid with this brocade fos collection?

Thanks and regards

**Comment by prasad-valmeti-broadcom** [comment]
Hi,
  We have logical_switch.yml playbook (from v1.3.2 onwards) to create logical switches. Please have a look at it and let us know if it solves your purpose.
Regards,
Prasad

**Comment by diazj1** [comment]
Yes.
Thanks for your help.
BR
