### ISSUE TITLE
msg Receive timeout.  with brocade_fos_command

### ISSUE THREAD

**Issue by kevinhuy** [brocade/ansible#15]
Hi 

My environnement 

ansible 2.9.1
python 2.7

i have random timeout issue when trying this playbook :

  - name: firmwaredownloadstatus
    brocade_fos_command:
      switch_login: admin
      switch_password: XXXXX
      switch_address: X.X.X.X
      command_set:
        - command: firmwareshow
          timeout: 120
    register: check_version

  - name: print ansible_facts gathered
    debug:
      var: check_version

I also noticed that before  upgrade to 8.2 the command did not have time to execute properly.

Error below 

TASK [firmwaredownloadstatus] ***************************************************************************************************************************************
task path: /home/xxx/git/ansible/brocade/tasks/test2.yml:12
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860 `" && echo ansible-tmp-1578993312.91-86715209149860="` echo /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860 `" ) && sleep 0'
Using module file /home/xxx/git/ansible/brocade/library/brocade_fos_command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-255796hHpRt/tmp85CEV6 TO /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/AnsiballZ_brocade_fos_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/ /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_brocade_fos_command_payload_RcfS5j/ansible_brocade_fos_command_payload.zip/ansible/modules/brocade_fos_command.py", line 322, in receive_until_match
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 667, in recv
    raise socket.timeout()

[WARNING]: Module did not set no_log for switch_password

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command_set": [
                {
                    "command": "firmwareshow",
                    "exit_tests": [],
                    "prompts": [],
                    "result_tests": [],
                    "start_state": [
                        {
                            "flag": "changed",
                            "value": false
                        },
                        {
                            "flag": "failed",
                            "value": false
                        }
                    ],
                    "timeout": 120
                }
            ],
            "global_timeout": 15,
            "hostkeymust": false,
            "switch_address": "",
            "switch_login": "admin",
            "switch_password": ""
        }
    },
    "messages": [
        "",
        "SSH into X.X.X.X",
        "Exiting due to error: ",
        [
            "firmwareshow",
            "Appl     Primary/Secondary Versions ",
            "------------------------------------------",
            "FOS      v8.2.1c",
            "         v8.2.1c",
            "DS_6505B:admin> "
        ]

**Comment by daniel-chung-broadcom** [comment]
Can you please post the question to https://github.com/brocade/ansible-fos-command? I'll forward the issue to some folks that might be able to help in the meanwhile.

**Comment by kevinhuy** [comment]
Hello

On the link, there no way to post a question.

Regards 

Envoyé de mon iPhone

**Comment by daniel-chung-broadcom** [comment]
I see.

I forwarded the question to folk who might be able to help.

**Comment by chipcopper** [comment]
Hi kevinhuy,

The brocade_fos_command module under the brocade account is actually a pull of my personal repository at github.com/chipcopper/brocade_fos_command.  It’s not officially supported by Brocade but because a number of people have found value in it, Brocade is posting a copy of it here.  Let’s close this issue here and reopen it under my personal repository.  It is probably just finding the timer settings that are suitable for your particular situation but if it is more than that, I will update the repository and Brocade can pull the latest copy.

I’m glad to hear you are looking at my module and I am optimistic that with the right playbook settings it will work for you as it has with others.

- Chip

**Comment by kevinhuy** [comment]
thanks for answer , i will do it .

**Comment by daniel-chung-broadcom** [comment]
closing the issue since forwarded to brocade_fos_command repo
