### ISSUE TITLE
switchshow

### ISSUE THREAD

**Issue by kevinhuy** [brocade/ansible#17]
hi 

More a question than an issue, is there a way to get wwn that is connected to port like switchshow ?

Regards

**Comment by jconsoli** [comment]
Kevin,

Yes.

There is a PyFOS utility, utils/switch/switch_show.py that generates the equivalent of the FOS switchshow command output. 

If this is a generic question about where to find that information in the API, I suggest joining the Brocade community at the link below. Search for: "Brocade Automation Community". You can post PyFOS questions there as well.

https://community.broadcom.com/home

**Comment by daniel-chung-broadcom** [comment]
closing based on the last reply.
