### ISSUE TITLE
Issue with adding members to Peer Zones

### ISSUE THREAD

**Issue by ihami** [brocade/ansible#18]
I am trying to test out adding new members to peer zones that already exist. I am making an assumption on how this works with the ansible modules. 

The first time the playbook runs it creates the aliases and zones with no issue. If I run a second time with no changes, it runs fine. 

If I try to add a new member to an existing peer zone the playbook errors out with the following. 

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "credential": {
                "fos_ip_addr": "dfwpocbs03",
                "fos_password": "xxxxxxxxxx",
                "fos_user_name": "xxxxxxxxx",
                "https": false
            },
            "members_add_only": true,
            "throttle": null,
            "vfid": -1,
            "zones": [
                {
                    "members": [
                        "testhost02"
                    ],
                    "name": "dfw_poc_fab_a_ansible_target1",
                    "principal_members": [
                        "ansible_target1"
                    ]
                },
                {
                    "members": [
                        "testhost02"
                    ],
                    "name": "dfw_poc_fab_a_ansible_target2",
                    "principal_members": [
                        "ansible_target2"
                    ]
                }
            ],
            "zones_to_delete": null
        }
    },
    "msg": "HTTP POST failed",
    "post_resp_code": 400,
    "post_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf",
            "error": [
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "-500",
                        "error-module": "zone"
                    },
                    "error-message": "Error: Incorrect 'zone-type' field detected for Peer Zone operation. Retry command with the proper 'zone-type' field.",
                    "error-path": "/zone/zone-name/dfw_poc_fab_a_ansible_target1/",
                    "error-tag": "Operation-failed",
                    "error-type": "protocol"
                },
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "-500",
                        "error-module": "zone"
                    },
                    "error-message": "Error: Incorrect 'zone-type' field detected for Peer Zone operation. Retry command with the proper 'zone-type' field.",
                    "error-path": "/zone/zone-name/dfw_poc_fab_a_ansible_target2/",
                    "error-tag": "Operation-failed",
                    "error-type": "protocol"
                }
            ]
        }
    },
    "post_resp_reason": "Bad Request",
    "post_url": "http://dfwpocbs03/rest/running/zoning/defined-configuration"
}

I call this playbook with the following extra-vars

"sanFabric=POC_SANA serverName=testhost02 wwnA=11:00:00:00:00:00:00:22"

createzone is the playbook
createzones is the main.yml in the role 
POC_SANA is the vars file for the the playbook 

[createzone.txt](https://github.com/brocade/ansible/files/4110794/createzone.txt)
[createzones.txt](https://github.com/brocade/ansible/files/4110723/createzones.txt)
[POC_SANA.txt](https://github.com/brocade/ansible/files/4110724/POC_SANA.txt)

**Comment by daniel-chung-broadcom** [comment]
I am having a bit of a hard time understanding how to repro the problem. I tried creating a peer zone with one regular and one principal member. Then I tried adding a new regular member and a new principal member with member_add_only. That scenario works ok for me by leaving me two members per each type. 

Would you be able to print out the debug output from your play? I want to see if I am able to specify the zoning inputs as your playbook is specifying. Thanks.

**Comment by ihami** [comment]
[zoneplaybook.txt](https://github.com/brocade/ansible/files/4148446/zoneplaybook.txt)

The attached is the debug output from the play. Let me know if you need any additional info.

**Comment by ihami** [comment]
[zoneplaybook.txt](https://github.com/brocade/ansible/files/4148454/zoneplaybook.txt)

Please find attached the debug output from the play run. Let me know if you need additional info.

**Comment by daniel-chung-broadcom** [comment]
I think I believe I reproduced the scenario. The scenario is to

1) create a peer zone
2) add a normal member only

Can you please confirm?

Thanks.

**Comment by ihami** [comment]
Correct, the initial creation works fine.

Its when trying to add a new member to an already existing peer zone is where the issue occurs.

Thanks.

---------------------------
Ian Hamilton
Sr. Storage Engineer
Work: (817) 262-6331
Mobile (972) 880-3204
[cid:image005.jpg@01CCF294.C76BE3C0]

**Comment by daniel-chung-broadcom** [comment]
based on my experiment, I believe adding a principal member (either along with another normal member or without) works ok. But adding a normal member-only fails.

**Comment by ihami** [comment]
Thanks Daniel, do you consider this a bug or working as designed?

In my zone variable, I have members and principal_members listed. I am not sure I understand
what changes I would need to make to get this to work based on your  information.

I think the proper way to do this would be to  have a peer_members variable for
peer zones.


            "zones": [
                {
                    "members": [
                        "testhost02_FCA"
                    ],
                    "name": "dfw_poc_fab_a_ansible_target1",
                    "principal_members": [
                        "ansible_target1"
                    ]
                },
                {
                    "members": [
                        "testhost02_FCA"
                    ],
                    "name": "dfw_poc_fab_a_ansible_target2",
                    "principal_members": [
                        "ansible_target2"
                    ]
                }
            ],

---------------------------
Ian Hamilton
Sr. Storage Engineer
Work: (817) 262-6331
Mobile (972) 880-3204
[cid:image005.jpg@01CCF294.C76BE3C0]

**Comment by daniel-chung-broadcom** [comment]
I believe it is a bug. Looking into the code.

**Comment by daniel-chung-broadcom** [comment]
Can you please try out the following branch? I tested add/delete of each type of members for peer zones. Also member add only mode as well for peer zones.

peer_add_normal_member_only

**Comment by ihami** [comment]
I have tested out this branch and it is now adding the peer zone members to existing zones as expected.

Thanks for the fix.



DFWPOCBS03:efcserver> zoneshow --peerzone all
Defined configuration:
zone:  dfw_poc_fab_a_ansible_target1
   Property Member: 00:02:00:00:00:03:01:01
   Created by: User
   Principal Member(s):
                ansible_target1
   Peer Member(s):
                testhost01_FCA; testhost02_FCA; testhost03_FCA
zone:  dfw_poc_fab_a_ansible_target2
   Property Member: 00:02:00:00:00:03:01:01
   Created by: User
   Principal Member(s):
                ansible_target2
   Peer Member(s):
                testhost01_FCA; testhost02_FCA; testhost03_FCA

Effective configuration:
zone:  dfw_poc_fab_a_ansible_target1
   Property Member: 00:02:00:00:00:03:01:01
   Created by: User
   Principal Member(s):
                22:22:33:44:55:66:77:99
   Peer Member(s):
                11:00:00:00:00:00:00:02
                11:00:00:00:00:00:00:22
                11:00:00:00:00:00:00:33
zone:  dfw_poc_fab_a_ansible_target2
   Property Member: 00:02:00:00:00:03:01:01
   Created by: User
   Principal Member(s):
                22:22:33:44:55:66:77:aa
  Peer Member(s):
                11:00:00:00:00:00:00:02
                11:00:00:00:00:00:00:22
                11:00:00:00:00:00:00:33

4 Peer Zones in Eff Cfg


---------------------------
Ian Hamilton
Sr. Storage Engineer
Work: (817) 262-6331
Mobile (972) 880-3204
[cid:image005.jpg@01CCF294.C76BE3C0]

**Comment by daniel-chung-broadcom** [comment]
Great. I'll close the issue when I have the changes merged into the main branch and distributed in the ansible galaxy. Thanks.

**Comment by daniel-chung-broadcom** [comment]
merged to main and published the latest collection on galaxy.ansible.com. Closing the issue.

**Comment by sboldt1978** [comment]
Hi Daniel,

I'm running in the same error that ihami described, but with the current version 1.3.3. Looking at the code it seems that your fix has been thrown out at some point in the past :-(
 @daniel-chung-broadcom  would you be so kind and fix this once more? Thanks a lot!

**Comment by prasad-valmeti-broadcom** [comment]
Hi,
   If you know a code change that is missing,  could you please share it here? That will help to resolve the issue quickly.
   At least files that are changed for this issue.
   Tried to compare peer_add_normal_member_only branch mentioned in this issue with v1.3.4, seems like both are the same now.
Regards,
Prasad
