### ISSUE TITLE
File based bulk zoning from current switch configuration

### ISSUE THREAD

**Issue by sri4kanne** [brocade/ansible#24]
Hello, 
I am able to create zones using the zones playbook. I was wondering if we can create bulk zoning based on csv file similar pyfos ?
Else if there is an easier way to convert configupload file into the yaml format that can be used to update config. We are hoping to keep this file in git and being able to version control and update zoning on switches using the Ansible playbook.

Please let me know if you need any more details.

Thanks,

**Comment by daniel-chung-broadcom** [comment]
I am thinking that if we can dump out the existing database into a file - pyfos based utility script (not sure if we can do facts gathering in yaml at first glance) - and include that into a playbook, that would satisfy your use case. 

For example. here is an example of alias in a db file.

dc400196@iaas-l-2206-611:~/ansible/tasks$ cat zoning_db.yml 
aliases:
  - name: Host1
    members:
      - 11:22:33:44:55:66:77:88
  - name: Target1
    members:
      - 22:22:33:44:55:66:77:99      


and here is the playbook that includes the file and reference the variable "aliases"

- hosts: san_eng_zone_seed_san_a
  gather_facts: False
  vars_files: zoning_db.yml

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: admin
      fos_password: fibranne
      https: False

  tasks:

  - name: Create aliases
    brocade_zoning_alias:
      credential: "{{credential}}"
      vfid: -1
      aliases: "{{aliases}}"
#      aliases_to_delete: "{{aliases_to_delete}}"


would something like this satisfy your use case?

**Comment by daniel-chung-broadcom** [comment]
while waiting for your comments, I pushed out some changes that we can examine to understand your requirements.

Here is the name of the branch:

existing_zone_db

under the task directory, I added the following files.

        new file:   zonedb.yml
        new file:   zoning_act.yml
        new file:   zoning_to_yml.py

zoning_to_yml.py is a pyfos utility script that is used to dump out the existing database in yml format. For example, I used the script to create zonedb.yml file by doing:

./zoning_to_yml.py -i xxx -L admin -P password > /tmp/zonedb.yml

you will need to install pyfos in your env before you can execute the script.

within zoning_act.yml, I added "vars_files" entry to reference zonedb.yml. The rest of the playbook is the same as zoning_zone.yml to executes tasks for alias, zone, and cfg.

Please let me know how these look. Thanks.

**Comment by sri4kanne** [comment]
I tried it out and works as you have mentioned!!
This is very helpful and reduced a lot of toil for us! thank you :)

**Comment by daniel-chung-broadcom** [comment]
great to hear.

I'll add some details to the files to provide additional context for others for usage

I will plan to leave the changes on the side branch for some time while I accumulate requests/defects fixes. I'll go ahead and close this issue once it gets merged into the main branch.

Thanks.

**Comment by daniel-chung-broadcom** [comment]
the changes have been merged to main and uplodated to galaxy.ansible.com. Closing the issue as agreed previously.
