### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by pain29-coder** [brocade/ansible#28]
Hi,

Trying use your module brocade_facts.py and setting a variable "https:" to  True. I am ending up with a "SSL: CERTIFICATE_VERIFY_FAILED". What path is the module trying to lookup the client certificates from. I don't see a path defined. Is it looking at the /etc/ssl/certs , the default local OS CA bundle for the cert. Is there an option/variable i could use to point to a different cert path and not OS CA bundle.

**Error:**
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)>

**Comment by daniel-chung-broadcom** [comment]
hi. Is your FOS switch self-signed or enterprise/CA signed?

**Comment by pain29-coder** [comment]
It is Enterprise CA signed certificate.

**Comment by daniel-chung-broadcom** [comment]
I believe it is looking at the default bundle from OS. So I would think that adding the issuer's cert to the local bundle would be one way to resolve the issue.

I haven't tried this specifically. But I would think that providing SSL_CERT_FILE or SSL_CERT_DIR might also work since ansible is executing python scripts underneath. 

Here is an article that I found online.

https://access.redhat.com/articles/2039753

and it talks about doing something like

SSL_CERT_FILE=/etc/rhsm/ca/redhat-uep.pem python urllib2-test.py https://cdn.redhat.com/

I guess you can try setting https to "self" instead of "True" as a temporary workaround if you cannot find adequate solutions right away. I believe that would allow you to skip the validation while still using encryption.

**Comment by autocoder10** [comment]
I am able to connect and work on the switch with https as "self" but still want to use "True" instead. Still getting the same "SSL: CERTIFICATE_VERIFY_FAILED" error even after trying different options when ran the playbook with https "True". Below is the process I did to try to fix this issue.

1. Added the switch cert file (.pem) to this location "/etc/rhsm/ca". Then added the env variable using "export SSL_CERT_FILE=/etc/rhsm/ca/<switch cert (.pem)> 
2. Added the switch cert file (.pem) to  this location "/usr/share/pki/ca-trust-source/" and ran the update-ca-trust. Ran the playbook with https "True". 
3. Created a simple py test script and ran the "SSL_CERT_FILE=/etc/rhsm/ca/<switch cert (.pem)> python3 test1.py". Did the same process with SSL_CERT_DIR "export SSL_CERT_DIR=/etc/rhsm/ca and still no luck.

**Comment by daniel-chung-broadcom** [comment]
I also think it makes the most sense to try to get the "True" to works as well.

I am not a security expert. So, I might have a misunderstanding here. But I thought that the cert that you should use is not the switch's cert but the issuer's cert (cert of your enterprise that is used to sign the FOS's cert), isn't it? My understanding is that linux host that you are running ansible-playbook on would need the issuer's cert to validate the cert that the FOS would send since the FOS's cert is signed by the issuer.

I have done most of my testing using an issuer that is already part of the OS bundle. Let me see if I could find some env that is missing the issuer's cert and see I could figure out a way to make this work. It might take some time to get this going. I'll keep you posted. Please also let me know if you make any progress and ideas to try.

Thanks.

**Comment by pain29-coder** [comment]
Basically the cert is installed on the switch. So when using python modules
it's trying to validate that connection before it makes rest API to work.
It's the same cert that's presented to you when you try logging in to the
switch fos using web url.

**Comment by daniel-chung-broadcom** [comment]
In my experiment, SSL_CERT_FILE method seems to work. Here is my console output.

**my playbook looks like this.**

- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: admin
      fos_password: xxx
      https: True

  tasks:

  - name: gather facts
    brocade_facts:
      credential: "{{credential}}"
      vfid: -1
      gather_subset:
        - brocade_snmp_system

  - name: print ansible_facts gathered
    debug:
      var: ansible_facts

**and SSL_CERT_FILE execution looks like this:**

dc400196@iaas-l-2206-611:~/ansible/tasks$ SSL_CERT_FILE=secp384r1CA.pem ansible-playbook -i ../san-inventory test.yml

PLAY [san_eng_zone_seed_san_a] *************************************************

TASK [gather facts] ************************************************************
ok: [san_eng_zone_seed_san_a]

TASK [print ansible_facts gathered] ********************************************
ok: [san_eng_zone_seed_san_a] => {
    "ansible_facts": {
        "brocade_snmp_system": {
            "audit_interval": "60",
            "contact": "Field Support.",
            "description": "Fibre Channel Switch.",
            "encryption_enabled": false,
            "informs_enabled": false,
            "location": "End User Premise.",
            "security_get_level": "0",
            "security_get_level_string": "no-security",
            "security_set_level": "3",
            "security_set_level_string": "no-access",
            "snmpv1_enabled": true
        },
        "discovered_interpreter_python": "/usr/bin/python3",
        "ssh_hostkeymust": true
    }
}

PLAY RECAP *********************************************************************
san_eng_zone_seed_san_a    : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

**And the same playbook without SSL_CERT_FIEL give me the cert verification fail:**

dc400196@iaas-l-2206-611:~/ansible/tasks$ ansible-playbook -i ../san-inventory test.yml

PLAY [san_eng_zone_seed_san_a] *************************************************

TASK [gather facts] ************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
fatal: [san_eng_zone_seed_san_a]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1122, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1167, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1118, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 944, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 887, in send\n    self.connect()\n  File \"/tmp/ansible_brocade_facts_payload_byj6rx_5/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\", line 430, in connect\n  File \"/usr/lib/python3.5/ssl.py\", line 377, in wrap_socket\n    _context=self)\n  File \"/usr/lib/python3.5/ssl.py\", line 752, in __init__\n    self.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 988, in do_handshake\n    self._sslobj.do_handshake()\n  File \"/usr/lib/python3.5/ssl.py\", line 633, in do_handshake\n    self._sslobj.do_handshake()\nssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/dc400196/.ansible/tmp/ansible-tmp-1588691984.3049881-277899994036050/AnsiballZ_brocade_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/dc400196/.ansible/tmp/ansible-tmp-1588691984.3049881-277899994036050/AnsiballZ_brocade_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/dc400196/.ansible/tmp/ansible-tmp-1588691984.3049881-277899994036050/AnsiballZ_brocade_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.brocade_facts', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/usr/lib/python3.5/runpy.py\", line 199, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_brocade_facts_payload_byj6rx_5/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py\", line 384, in <module>\n  File \"/tmp/ansible_brocade_facts_payload_byj6rx_5/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py\", line 181, in main\n  File \"/tmp/ansible_brocade_facts_payload_byj6rx_5/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_connection.py\", line 56, in login\n  File \"/tmp/ansible_brocade_facts_payload_byj6rx_5/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\", line 1390, in open_url\n  File \"/tmp/ansible_brocade_facts_payload_byj6rx_5/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_brocade_facts_payload_byj6rx_5/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\", line 448, in https_open\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
san_eng_zone_seed_san_a    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  

**Here is the output from seccertmgmt show -cert https showing the issuer's information:**

Issued By 
    countryName               = US
    stateOrProvinceName       = Colorado
    localityName              = Broomfield
    organizationName          = Brocade BU
    organizationalUnitName    = FOS SQA

**And here is the output of openssl showing the CN of the cert in secp384r1CA.pem:**

        Subject: C=US, ST=Colorado, L=Broomfield, O=Brocade BU, OU=FOS SQA, CN=xxx

The cert being used by ansible-playbook is a cert of the issuer that signed the cert installed on the FOS switch. I also confirmed with our security folks on the usage.

I didn't try using the cert installed on the FOS switch in the ansible-playbook execution.

**Comment by autocoder10** [comment]
Thanks for the info Daniel. I tried the process and the playbook is working now with the https "True". Really appreciate your help.

**Comment by daniel-chung-broadcom** [comment]
Great to hear. Glad that I was able to help.
