### ISSUE TITLE
Looking for couple modules...

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#29]
Hi, I am looking for couple modules related to the zoning/un-zoning tasks. 
1. We have one active zone cfg with lot of zone members in it and planning to remove one or multiple zone members from the active cfg. Is there any module our there that I can use to perform this task? 

Cli commad to remove a zone member from active zone cfg:
cfgremove   "<active cfg_name>, "<zone_name>"

Example:  
Active zone cfg name: newcfg1
Zone members: Zone1
                          Zone2
                          Zone3 ---> Just want to remove this one 

2.  Currently we are performing the nodefind command to check and make sure the host/target WWPN is logged into the fabric correctly before performing the zoning tasks. I don't see it anywhere in the GitHuband and is there any way can I get that module?

**Comment by daniel-chung-broadcom** [comment]
1. I think the easiest way to do this would be to dump your current db using tasks/zoning_to_yaml.py script. This is a pyfos dependent script. What the script does is to dump out the full zoning db in yaml format that can be used by tasks/zoning_act.yml playbook. Then you can go ahead and remove the zones that you want removed from the cfg and ansible-playbook zoning_act.yml. 

2) Are you looking for that module in ansible or would pyfos dependent script be sufficient? If you are familiar with pyfos, you can find the script under pyfos/utils/misc/device_find.py. The script will search through the NS using the WWN provided to indicate if the device is known by NS, if the device is defined as an alias in zoning db, if the device is being by any zones, and if the device is part of effective config.

Please let me know if you are looking for something different or the answers doesn't satisfy your specific use case or env.

**Comment by autocoder10** [comment]
Thanks Daniel for the info. I am not that familer with PyFOS and we are primarly focusing on Ansible for automation. I will take look at the first one but for the second one looking for the ansible related ones.

**Comment by daniel-chung-broadcom** [comment]
ok. let me know how it goes for the first case.

in the meanwhile, I'll look into what the second one would look like and get back to you. I'll keep you posted.

**Comment by autocoder10** [comment]
Daniel, For the first one to remove one or multiple zone members from the active cfg, I am checking **library/brocade_zoning_cfg.py** module where we are using **"members_add_only"** in the playbook to add the new zone member(s) to active cfg. Can we have a similar option "members_remove_only"  to remove a member(s) instead of going through the process you described earlier?
      
        cfgs=dict(required=False, type='list'),
        **members_add_only=dict(required=False, type='bool'),**
        cfgs_to_delete=dict(required=False, type='list'),
        active_cfg=dict(required=False, type='str'))

Also yesterday during my testing, I noticed if we don't mentioned "members_add_only" and run the playbook only with "cfgs" it will add the new member that we mention and remove all the existing around 100 zone members (using cfgremove cmd) from the active zone config.

Info	No	Thu May 07 2020 15:25:58 CDT	8.2.1c, , , , , , Event: cfgadd, Status: success, Info: Zone(s) 
Info	No	Thu May 07 2020 15:25:59 CDT	8.2.1c, , , , , , Event: cfgremove, Status: success, Info: Zone(s)

**Comment by daniel-chung-broadcom** [comment]
correct. the module is meant to take the members as the "final" set and add/delete to match the resulting database to the list that is provided. members_add_only was to help with use cases where you are dealing with a large existing database - exactly the same scenario as yours I think. One thing to remember is that, we also didn't have zoning_to_yml.py to pull the full database to start from. Later on, another customer wanted to keep the full database in github.com to version control and also use as part of playbook. So, that is why we created zoning_to_yml.py to help with that.

In a long run, I think that might be an easier strategy to maintain since you are keeping your full db in your playbook to version control, dry run and apply fully, instead of creating individual playbooks to add some members, delete some members, etc.

getting back to members_remove_only, I think what you are looking for is for the playbook to have a list of zones and members. And in that case, you will be removing all the members from the zones. As an example, you will end up with a DB that has Host1, Target1, and Target2 removed from NewZoneName if you play this playbook below, right? 

  - name: delete members from zone.
    brocade_zoning_zone:
      credential: "{{credential}}"
      vfid: -1
      members_delete_only: True
      zones:
      - name: NewZoneName
        members:
          - Host1
          - Target1
          - Target2

**Comment by autocoder10** [comment]
I think I confused with the term "members" when talked about the active zone cfg DB and sorry about that. Let's me explain in a different way. 
I can delete the zones (which has members in it) if they are not in the active zone cfg as expected. But if  I want to delete the exact same zones that are in active zone cfg DB then I need to remove the zones from the active zone cfg DB first and then delete that zone.

This is the playbook I am using to create the new zone "NewZoneName" which was executed successfully. 
    zones:
      - name: NewZoneName
        members:
          - Host1
          - Target1      
  tasks:
  - name: Create zones
    brocade_zoning_zone:
      credential: "{{credential}}"
      vfid: -1
      zones: "{{zones}}"

This is the playbook I am using to add the newly created zone "NewZoneName" from above to the existing active zone cfg DB "SANA" and enabling it "SANA". NOTE: Not creating new zone cfg DB.
    cfgs:
      - name: SANA
        members:
          - NewZoneName
  tasks:
  - name: Create cfgs
    brocade_zoning_cfg:
      credential: "{{credential}}"
      vfid: -1
      cfgs:  "{{cfgs}}"
      members_add_only: True
      active_cfg: SANA

So, can we have something to remove the zone "NewZoneName" that we added to active zone cfg DB "SANA"? 

**For example:
    cfgs:
      - name: SANA
        members:
          - NewZoneName
  tasks:
  - name: Remove cfgs
    brocade_zoning_cfg:
      credential: "{{credential}}"
      vfid: -1
      cfgs:  "{{cfgs}}"
      members_remove_only: True
      active_cfg: SANA**

Once the zone is removed from the active zone cfg DB then I can use below playboot to delete that zone.

    zones_to_delete:
      - name: NewZoneName
  tasks:
  - name: Create zones
    brocade_zoning_zone:
      credential: "{{credential}}"
      vfid: -1
      zones_to_delete: "{{zones_to_delete}}"

**Comment by daniel-chung-broadcom** [comment]
I just pushed some changes that I believe aligns with what you are looking to do. Can you please check out my side branch of  zone_remove? You can find some examples of what you are looking to do in zoning_zone_members_remove_only.yml. I ran zoning_zone.yml first to enable cfg1 that contains both Zone1 & Zone2. Using zoning_zone_members_remove_only.yml, I am able to leave cfg1  enabled while removing Zone1 from it.

Please check it out and let me know if this is what you are looking for. If so, we'll do additional documentation, etc.

btw, zoning_to_yml.py will create a cfg list that contains all your zones. And you can then use the full list to add/remove zones to apply playbooks. I know that this is not exactly what are you looking to do. But I think having a full dump of your database might be useful in the long run. Just a friendly suggestion to check out the script when you get a chance. :-)

I'll take a look at the nodefind aspects of the playbook. I'll keep you posted.

**Comment by autocoder10** [comment]
I have tested the remove module to remove zone from active zone cfg DB and it worked perfectly.... Thanks for updating and sharing the modules. I will look into the zoning_to_yml.py process as well as you suggested. Thanks again!!.

**Comment by daniel-chung-broadcom** [comment]
Great to hear. I'll plan to add additional documentation.

I typically wait a few weeks to accumulate changes and go through sanity testing before merging the branch into master. I'll leave the issue open until then.

Also, I just pushed some changes to the side branch to search NS based on some attributes. I don't know how closely it resembles nodefind. I am doing bit a research. But in the meanwhile, do you mind checking it out? The playbooks are find_ns_by_pwwn.yml and find_ns_by_pid.yml. These use a list facts module that is meant to be a generic template for finding an object from a list that matches attributes specified. Please let me know if this aligns with what you are looking for or you are looking for something else.

**Comment by autocoder10** [comment]
I have tested both playbooks find_ns_by_pwwn.yml and find_ns_by_pid.yml. I got the same below output for both playbooks. It has lot of information which is kind of useful but basically looking for main fields like **"port_index", "port_name", "link_speed"** and also looking for **"Aliases:"** which mentiones the alias name for that WWPN if it is created or shows empty if it is new host/target.

    "ansible_facts": {
        "fibrechannel-name-server": [
            {
                "cascaded_ag": "no", 
                "class_of_service": "class-3", 
                "connected_through_ag": "no", 
                "fabric_port_name": "2x:xx:xx:xx:xx:xx:xx:xx", 
                "fc4_features": "FCP-Initiator FCP-Target", 
                "fc4_type": "FCP", 
                "fcoe_device": "no", 
                "frame_redirection": "no", 
                "link_speed": "8G", 
                "lsan": null, 
                "name_server_device_type": "Physical Initiator+Target", 
                "node_name": "5x:xx:xx:xx:xx:xx:xx:xx", 
                "node_symbolic_name": null, 
                "partial": "no", 
                "permanent_port_name": "5x:xx:xx:xx:xx:xx:xx:xx", 
                "port_id": "0x05XXXX", 
                "port_index": "13", 
                "port_name": "5x:xx:xx:xx:xx:xx:xx:xx", 
                "port_properties": null, 
                "port_symbolic_name": null, 
                "port_type": "n-port", 
                "real_device_behind_ag": "no", 
                "share_area": "no", 
                "slow_drain_device_quarantine": "no", 
                "state_change_registration": null
            }
        ]
    }
}

Actual nodefind output from the switch:

 nodefind 5x:xx:xx:xx:xx:xx:xx:xx
Remote:
    Type Pid    COS     PortName                NodeName
    N    05XXXX;      3;5x:xx:xx:xx:xx:xx:xx:xx;5x:xx:xx:xx:xx:xx:xx:xx;
        FC4s: FCP
        Fabric Port Name: 2x:xx:xx:xx:xx:xx:xx:xx
        Permanent Port Name: 5x:xx:xx:xx:xx:xx:xx:xx
        Device type: Physical Initiator+Target
        Port Index: 13
        Share Area: No
        Redirect: No 
        Partial: No
        Slow Drain Device: No
        Device Link speed: 8G
        Connected through AG: No
        Real device behind AG: No
        FCoE: No
        FC4 Features [FCP]: Initiator Target 
    **Aliases: <alias_name>   -----> looking for this field as well**

**Comment by daniel-chung-broadcom** [comment]
yes, the playbook returns the full ns attribute that contains everything. Not sure if it is possible to display portion of the returned structure within playbook. I'll need to look into that. I guess we can also specify the attributes to be displayed in the module but I think doing it within yml might provide us with more flexibility.

As for zoning, I think we should be able to do something about that based on zoning output. I'll need to look into that as well.

**Comment by daniel-chung-broadcom** [comment]
I just added an example of printing limited number of fields from the found ns entry. Can you please checkout find_ns_by_pwwn.yml?

zoning looks to be bit more complicated. still looking into it.

**Comment by autocoder10** [comment]
I have tested it and got this info which is awesome. But I am bit confused of what "zoning" you are referring to? Do you mean **Aliases** field (which is showing in nodefind CLI cmd) that I am looking from "find_ns_by_pwwn.yml"? 

{
    "msg": "device with Port WWN of \"5x:xx:xx:xx:xx:xx:xx:xx\" is found at Port Indext of \"13\". The device's speed is \"8G\""
}

**Comment by daniel-chung-broadcom** [comment]
yes. as far as I can tell, alias is not part of ns entry returned and parsed. So, I'll need to pull zoning database and basically search for the wwn the list of aliases. I think that requires nested loop and I don't see an easy example for something like that online. I think I can bake everything into the same playbook (assuming that I can figure out how to parse aliases), I think, but will need to be separate tasks, I think.

**Comment by daniel-chung-broadcom** [comment]
can you please checkout the latest find_ns_by_pwwn.yml on remove_zone branch? It doesn't seem like there is an easy way to parse through defined-configuration in yml. So, I just wrote a specific module to search for wwn in alias and add the task in the playbook. Let me know how it looks.

**Comment by autocoder10** [comment]
I tested the new playbook with new library module and for the alias part shows it's skipping.  

Here is the playbook output:

ansible-playbook find_ns_by_pwwn.yml

PLAY [SANSwitches] **************************************************************************************************************************************************************************

TASK [gather device info] *******************************************************************************************************************************************************************
ok: []

TASK [print device information matching port_name] ******************************************************************************************************************************************
{
    "msg": "device with Port WWN of \"5x:xx:xx:xx:xx:xx:xx:xx\" is found at Port Indext of \"13\". The device's speed is \"8G\""
}

TASK [gather device alias info] *************************************************************************************************************************************************************
ok: 

TASK [print device alias information matching port_name] ************************************************************************************************************************************
skipping: [xxxxx]

PLAY RECAP **********************************************************************************************************************************************************************************
                  : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
it will "skip" if the wwn doesn't show up in any aliases. That also applies to the device information as well: if the device isn't in the NS, the specific task to display the device info will also "skip".

Can you try adding an alias with the WWN and see what that does?

**Comment by autocoder10** [comment]
The WWPN I tried has already an alias name to it but still it skipped.

**Comment by daniel-chung-broadcom** [comment]
I tested with alias with multiple entries. The code didn't work properly with alias with single member. Just pushed the changes. Can you check to see if your alias had just one WWN only? If so, can you try out the latest?

**Comment by autocoder10** [comment]
The WWPN I am testing with is the only member in that alias. I tested the "find_ns_by_pwwn.yml" playbook with new library module "brocade_zoning_alias_facts_by_wwn.py" and it's still skipping.

**Comment by daniel-chung-broadcom** [comment]
I am out of ideas. I think it would be best to get the debug output and see what I am missing here. Can you pull down the latest zone_remove branch and run the playbook with -vvvv option and send me the output?

For example, mine looks like this below. I tested for the wwn that ends with "ab" as well as "aa". So, in my case, the code is able to find the alias with one or multiple members. 

If you can send me your output, I can check to see what I am missing in my test scenarios. FYI. the output will contain the actual WWNs and I am not sure how comfortable you are with sharing the real device's WWNs.

TASK [gather device alias info] ************************************************
task path: /home/dc400196/ansible/tasks/test.yml:55
<san_eng_zone_seed_san_a> ESTABLISH LOCAL CONNECTION FOR USER: dc400196
<san_eng_zone_seed_san_a> EXEC /bin/sh -c 'echo ~dc400196 && sleep 0'
<san_eng_zone_seed_san_a> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dc400196/.ansible/tmp/ansible-tmp-1589334204.1571398-196235791210576 `" && echo ansible-tmp-1589334204.1571398-196235791210576="` echo /home/dc400196/.ansible/tmp/ansible-tmp-1589334204.1571398-196235791210576 `" ) && sleep 0'
Using module file /home/dc400196/ansible/library/brocade_zoning_alias_facts_by_wwn.py
<san_eng_zone_seed_san_a> PUT /home/dc400196/.ansible/tmp/ansible-local-216147htz0487g/tmph3qoigdt TO /home/dc400196/.ansible/tmp/ansible-tmp-1589334204.1571398-196235791210576/AnsiballZ_brocade_zoning_alias_facts_by_wwn.py
<san_eng_zone_seed_san_a> EXEC /bin/sh -c 'chmod u+x /home/dc400196/.ansible/tmp/ansible-tmp-1589334204.1571398-196235791210576/ /home/dc400196/.ansible/tmp/ansible-tmp-1589334204.1571398-196235791210576/AnsiballZ_brocade_zoning_alias_facts_by_wwn.py && sleep 0'
<san_eng_zone_seed_san_a> EXEC /bin/sh -c '/usr/bin/python3 /home/dc400196/.ansible/tmp/ansible-tmp-1589334204.1571398-196235791210576/AnsiballZ_brocade_zoning_alias_facts_by_wwn.py && sleep 0'
<san_eng_zone_seed_san_a> EXEC /bin/sh -c 'rm -f -r /home/dc400196/.ansible/tmp/ansible-tmp-1589334204.1571398-196235791210576/ > /dev/null 2>&1 && sleep 0'
ok: [san_eng_zone_seed_san_a] => {
    "alias_list": [
        {
            "alias-name": "myalia1s",
            "member-entry": {
                "alias-entry-name": [
                    "11:22:33:44:55:66:77:ab",
                    "11:22:33:44:55:66:77:aa"
                ]
            }
        },
        {
            "alias-name": "myalias",
            "member-entry": {
                "alias-entry-name": "11:22:33:44:55:66:77:aa"
            }
        }
    ],
    "ansible_facts": {
        "alias": [
            {
                "alias-name": "myalia1s",
                "member-entry": {
                    "alias-entry-name": [
                        "11:22:33:44:55:66:77:ab",
                        "11:22:33:44:55:66:77:aa"
                    ]
                }
            }
        ]
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "credential": {
                "fos_ip_addr": "10.155.107.74",
                "fos_password": "fibranne",
                "fos_user_name": "admin",
                "https": false
            },
            "throttle": null,
            "vfid": -1,
            "wwn": "11:22:33:44:55:66:77:aB"
        }
    }
}

TASK [print device alias information matching port_name] ***********************
task path: /home/dc400196/ansible/tasks/test.yml:61
ok: [san_eng_zone_seed_san_a] => {
    "ansible_facts['alias']": [
        {
            "alias-name": "myalia1s",
            "member-entry": {
                "alias-entry-name": [
                    "11:22:33:44:55:66:77:ab",
                    "11:22:33:44:55:66:77:aa"
                ]
            }
        }
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
san_eng_zone_seed_san_a    : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

**Comment by autocoder10** [comment]
I'm now able to see the alias name, it's members and other details related to the wwpn. Really appreciate your help and support.

**Comment by daniel-chung-broadcom** [comment]
Great. I'll leave the issue open until I am ready to merge the zone_remove branch into the main. Thanks.

**Comment by daniel-chung-broadcom** [comment]
zone_remove branch is merged & latest galaxy collection uploaded.

closing the issue.
