### ISSUE TITLE
switch config upload module

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#38]
I got a request to implement config upload before running zoning/un-zoning playbooks in Ansible. Is there any module our there that I can use to perform this configupload task?. Please let me know.

**Example from CLI:**
switch:admin> configupload
Protocol (scp, ftp, sftp, local) [ftp]: 
Server Name or IP Address [host]: 
User Name [user]: 
Path/Filename [<home dir>/config.txt]: 
Section (all|chassis|FID# [all]): 
username@<Server Name or IP Address> password:
Password:

**Comment by ihami** [comment]
This is how I did it. 
---
  - name: Backup Switch Config
    vars:

      timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      backupcommand: "{{ 'configupload -p scp serverip,user,/backupdir/' ~ switchName ~ '_' ~ timestamp }}"

    brocade_fos_command:

      switch_login: "{{ user }}"
      switch_password: "{{ vault_password }}"
      switch_address: "{{ switchName  }}"
      command_set:

        - command: "{{ backupcommand }}"
          prompts:
            - question: password
              response: "{{ svclxstg_password }}"

    register: configout

**Comment by daniel-chung-broadcom** [comment]
good recommendation from ihami. brocade_fos_command is a way to play cli as part of ansible playbook. So, that should definitely work.

I think the original request seems to indicate the need to save zoning db ("before zoning/unzoning playbook") Did I get that correctly? Would dumping out full zoning db be what you are looking for? If that is the case, I do have pyfos script zone_to_yml.py in tasks directory that you can use to dump the defined configuration in yml format to screen. You can then pipe that output into a file and that file can be integrated into zoning playbook. You can take a look at 

1) zonedb.yml - this is the screen capture of zoning_to_yml.py
2) zoning_to_yml.py - pyfos script to dump out the db. you can --help to find the options required.
3) zoning_act.yml - this is the playbook that applies the zonedb.yml.

This was requested specifically by a customer who wanted to dump out the full zoning db, version control and use it within a playbook to dry-run and apply changes.

**Comment by autocoder10** [comment]
Thanks ihami and Daniel for the recommendations. I will give it a try but quick question though. I think ansible fos-command module uses SSH connection instead of REST HTTPS to the switches right?? Why I asked because we are planning to use only REST method for now.

**Comment by daniel-chung-broadcom** [comment]
You are right, ansible fos-command module uses SSH.

zoning_to_yml.py uses pyfos, which in turn use REST HTTPS to connect to FOS switch. Also, all the zoning Ansible modules also use REST only.

All the Ansible modules use primarily REST but few modules cover handful of attributes through SSH on the backend. But if you don't list out the attributes handled by SSH in the playbook, SSH won't be triggered. Only REST willl.

**Comment by autocoder10** [comment]
daniel, the playbooks you mentioned just provides the zoning db and I am looking to backup the entire switch config which contains big list of configuration details like fcRouting, Chassis Configuration, Boot Parameters and .......using the configupload command. Also, I have tried the playbook which ihami shared which uses SSH to connect to the switch and we don't want to use SSH. So, is there any REST module that I can use to grab all this information from the switches.

**Comment by daniel-chung-broadcom** [comment]
yes, I suggested those things since you mentioned zoning/unzoning in the original issue.

I think we might be able to address your use case by updating the facts.yml to dump all rest module/objects that are available. Let me send you a updates facts.yml and see if that address your issue. Can I ask which FOS you are running?

**Comment by autocoder10** [comment]
Sure daniel. We are currently on FOS version = v8.2.1c.

**Comment by daniel-chung-broadcom** [comment]
To understand the requirements better, is the use case primarily to get a copy of everything REST for the moment? facts output will be in json format and to screen output - should be able to pipe to a file to save the content. So, it won't be used by another exiting playbooks. Is that ok? Is the use case primarily to keep the old database for reference?

**Comment by autocoder10** [comment]
You are correct. We want to backup the switch config before we perform zoning/un-zoning tasks just to be on the safe side if something goes wrong during the zoning/un-zoning activity and need to re-stored the config back to the switch.

**Comment by daniel-chung-broadcom** [comment]
Can you please take a look at tasks/template_facts_all.yml in docfixes branch? I tried to capture all the rest modules and objects but I manually walked through the yang files under 8.2.1c. So, it is possible that I missed some. Also, the switch that I tried the playbook on is very sparsely configured. So, my testing may not have been all that comprehensive. Can you please check out it and see if this is along the line of what you are looking for?

**Comment by autocoder10** [comment]
Sry for the delayed response. The playbook you gave is great and worked perfectly. Really appreciate your help.
I have one more quick request. Is there any Ansible module that I can use to run the below CLI commands to clone the existing zonedb config and just to save it on the switch itself and do not enable it.

zoneObjectCopy "objectName", "newName"
cfgsave "newName"

**Comment by daniel-chung-broadcom** [comment]
great to hear.

as for the zoneobjectcopy, let me look into and get back to you. I don't think we have specific rest API coverage for zoneobjectcopy but it feels like it should be simple enough to replicate the behavior using the existing APIs. I'll keep you posted.

**Comment by daniel-chung-broadcom** [comment]
just pushed some changes to docfixes branch. Can you please check it out and see if it is what you are expecting? The playbook is zoning_copy.yml and it uses brocade_zoning_copy. There is no rest API that directly maps to zoneobjectcopy. So, I added code to brocade_zoning_copy module to mimic the behavior and there might be some differences but should largely mirror. Please check it out and see if everything looks ok.

**Comment by autocoder10** [comment]
I'm getting the below error.. I did the troubleshooting and couldn't find the issue of what cause that error. 

TASK [copy CFG cfg1 to cfg1_new] ******************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'str_to_yang'
fatal: [xxxxxxx]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/andysc4/.ansible/tmp/ansible-tmp-1593181580.48-90565069633897/AnsiballZ_brocade_zoning_copy.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/andysc4/.ansible/tmp/ansible-tmp-1593181580.48-90565069633897/AnsiballZ_brocade_zoning_copy.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/andysc4/.ansible/tmp/ansible-tmp-1593181580.48-90565069633897/AnsiballZ_brocade_zoning_copy.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.brocade_zoning_copy', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_brocade_zoning_copy_payload_3mfyed7m/ansible_brocade_zoning_copy_payload.zip/ansible/modules/brocade_zoning_copy.py\", line 95, in <module>\n  File \"/tmp/ansible_brocade_zoning_copy_payload_3mfyed7m/ansible_brocade_zoning_copy_payload.zip/ansible/module_utils/brocade_connection.py\", line 13, in <module>\n  File \"/tmp/ansible_brocade_zoning_copy_payload_3mfyed7m/ansible_brocade_zoning_copy_payload.zip/ansible/module_utils/brocade_url.py\", line 13, in <module>\nImportError: cannot import name 'str_to_yang'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by daniel-chung-broadcom** [comment]
that's strange. I tested with cfg that is enabled as well as it is not. It feels more like env issue where brocade_yang.py wasn't found properly. do you mind trying the playbook with -vvvv option and send me the stack output? thansk.

**Comment by autocoder10** [comment]
PLAYBOOK: zoning_copy.yml *************************************************************************************************************************************************************************************
1 plays in zoning_copy.yml

PLAY [all] ****************************************************************************************************************************************************************************************************
META: ran handlers

TASK [copy CFG cfg1 to cfg1_new] ******************************************************************************************************************************************************************************
task path: /home/andysc4/ansible-brocade/ansible-docfixes/tasks/zoning_copy.yml:16
<xxxxxxx> ESTABLISH LOCAL CONNECTION FOR USER: andysc4
<xxxxxxx> EXEC /bin/sh -c 'echo ~andysc4 && sleep 0'
<xxxxxxx> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422 `" && echo ansible-tmp-1593186331.08-184312429071422="` echo /home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422 `" ) && sleep 0'
Using module file /home/andysc4/ansible-brocade/ansible-docfixes/tasks/library/brocade_zoning_copy.py
<xxxxxxx> PUT /home/andysc4/.ansible/tmp/ansible-local-106253F7xHN/tmpKXWePt TO /home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/AnsiballZ_brocade_zoning_copy.py
<xxxxxxx> EXEC /bin/sh -c 'chmod u+x /home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/ /home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/AnsiballZ_brocade_zoning_copy.py && sleep 0'
<xxxxxxx> EXEC /bin/sh -c 'SSL_CERT_FILE=/home/andysc4/ansible-brocade/dfs_lab_g2_chain.pem /usr/bin/python3 /home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/AnsiballZ_brocade_zoning_copy.py && sleep 0'
<xxxxxxx> EXEC /bin/sh -c 'rm -f -r /home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/AnsiballZ_brocade_zoning_copy.py", line 102, in <module>
    _ansiballz_main()
  File "/home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/AnsiballZ_brocade_zoning_copy.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/AnsiballZ_brocade_zoning_copy.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.brocade_zoning_copy', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_brocade_zoning_copy_payload__mldjsdw/ansible_brocade_zoning_copy_payload.zip/ansible/modules/brocade_zoning_copy.py", line 95, in <module>
  File "/tmp/ansible_brocade_zoning_copy_payload__mldjsdw/ansible_brocade_zoning_copy_payload.zip/ansible/module_utils/brocade_connection.py", line 13, in <module>
  File "/tmp/ansible_brocade_zoning_copy_payload__mldjsdw/ansible_brocade_zoning_copy_payload.zip/ansible/module_utils/brocade_url.py", line 13, in <module>
ImportError: cannot import name 'str_to_yang'
fatal: [xxxxxxx]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/AnsiballZ_brocade_zoning_copy.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/AnsiballZ_brocade_zoning_copy.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/andysc4/.ansible/tmp/ansible-tmp-1593186331.08-184312429071422/AnsiballZ_brocade_zoning_copy.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.brocade_zoning_copy', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_brocade_zoning_copy_payload__mldjsdw/ansible_brocade_zoning_copy_payload.zip/ansible/modules/brocade_zoning_copy.py\", line 95, in <module>\n  File \"/tmp/ansible_brocade_zoning_copy_payload__mldjsdw/ansible_brocade_zoning_copy_payload.zip/ansible/module_utils/brocade_connection.py\", line 13, in <module>\n  File \"/tmp/ansible_brocade_zoning_copy_payload__mldjsdw/ansible_brocade_zoning_copy_payload.zip/ansible/module_utils/brocade_url.py\", line 13, in <module>\nImportError: cannot import name 'str_to_yang'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

PLAY RECAP ****************************************************************************************************************************************************************************************************
xxxxxxx                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
that really doesn't provide any additional color. :-) I am definitely not seeing any issues in my view. So, I think we need to figure out what is the difference.

Can you please check couple of things?

1) do you see brocade_yang.py under utils directory?
2) within the brocade_yang.py, do you see this? 

def str_to_yang(istring):
    return istring.replace("_", "-")

**Comment by autocoder10** [comment]
Can you please check couple of things?

1. do you see brocade_yang.py under utils directory? **---- Yes.**
2. within the brocade_yang.py, do you see this?   **--- Not able to see the below lines in brocade_yang.py**
def str_to_yang(istring):
return istring.replace("_", "-")

**Comment by daniel-chung-broadcom** [comment]
it seems like your brocade_yang.py might be an old version. Can you try

"git status"

and see if brocade_yang.py is your private copy and came from docfixes branch?

**Comment by autocoder10** [comment]
Out lab env is down.. will test it with the updated modules and update here once our env is up.

**Comment by autocoder10** [comment]
I have tested the zoning_copy playbook with the current active cfg copy and it worked great. Quick question though. Is there any possibility to overwrite the same new cfg copy  every time we perform any zoning changes instead of creating the new one?

**Comment by daniel-chung-broadcom** [comment]
sounds good. Let me know how the testing goes.

As for the second question, can you please clarify. If you are referring to brocade_zoning_copy A->B overwriting the content of B if A was changed, that is how it behaves today. But I am not certain that that is what you meant.

**Comment by autocoder10** [comment]
You are correct. I think I got confused with the copy process. I'm good for now. Thanks for the zoneobjectcopy module.

**Comment by daniel-chung-broadcom** [comment]
Great to hear. I'll hold unto the changes and the issue for few days to potentially lump together with other changes for a sanity check and will close the issue once merged to master and published on galaxy.ansible.com.

**Comment by daniel-chung-broadcom** [comment]
merged to master and also a collection is uploaded to brocade name space in galaxy.ansible.com.
