### ISSUE TITLE
Module error from AWX 

### ISSUE THREAD

**Issue by bhanukana** [brocade/ansible#41]
Hello  Team,

I had run the all playbooks they are absolutely running fine. 
But facing error from AWX , because of modules, it throws me an error , as I it's not able to find the modules , which are been exported to particular directory .

Tried doing through  ansible environment , but still getting error .

Could you support .

Thanks.
Bhanu

**Comment by daniel-chung-broadcom** [comment]
I noticed that ansible awx requires specific directory structures. So, I created a new branch tower_awx that we can maintain to restructure the master branch content to work in awx env. Can you please try out the branch?

https://github.com/brocade/ansible/tree/tower_awx

I created a readme content specific to awx based on what I tried and I verified facts.yml and zoning_zone.yml.

Please let me know how this works for you.

**Comment by daniel-chung-broadcom** [comment]
just a friendly reminder. Can you please comment as to if the branch tower_awx has addressed your issues? Thanks.

**Comment by bhanukana** [comment]
Hello Daniel, I just saw that please give some time will update you ..

**Comment by daniel-chung-broadcom** [comment]
Thanks for the response. Please let me know if you run into any issues. I updated the readme content on tower_awx branch based on what I was able to run. So, hopefully, it will be helpful.

**Comment by bhanukana** [comment]
I just done testing it worked fine .
Thanks for the new update Daniel.

**Comment by daniel-chung-broadcom** [comment]
Great to hear. I plan to regularly update this branch to match the latest master branch content. Please let me know if any issues in the future. Thanks.

**Comment by mamoep** [comment]
Can‘t you fix the master branch to be compatible to AWX?

**Comment by daniel-chung-broadcom** [comment]
I am bit wary of making that change for the moment. It definitely isn't a lot of changes but I am not sure if everyone is going to be happy with the change if I go ahead. For example, issue of grabbing the fos_ip_addr from the inventory file vs. ability to get it from inventory/awx while using localhost might trip some folks over. Do you see needing to use tower_awx branch in awx env a major issue?

**Comment by daniel-chung-broadcom** [comment]
mamoep,

Do you mind opening a separate issue to track this input? I am playing around a bit and I think I might be able to make changes that would be fairly non-disruptive for non-awx users but still incorporate the changes needed for awx. I'll need to look through it bit more but I think it would be best if we can keep a separate issue to track this new request. Thanks.
