### ISSUE TITLE
Make master branch / collection compatible to AWX

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#48]
In issue #41 a seperate branch for AWX / Tower compatibility was built. I would like to have a compatible master branch. New users will be confused by this branch approach and Brocade customers are potentially bigger companies with use cases and budget for AWX.

**Comment by daniel-chung-broadcom** [comment]
thanks for filing the issue. looking at the details of consolidating the Linux git use model vs. awx use model. I'll keep you posted on the progress.

**Comment by daniel-chung-broadcom** [comment]
awx/tower branch merged to master & updated galaxy.
