### ISSUE TITLE
Module pyfos_brocade_fibrechannel not found in PyFOS

### ISSUE THREAD

**Issue by meersjo** [brocade/ansible#5]
I've installed PyFOS 1.2.0 from the github repo (including prereqs), but I'm getting the message `ImportError: No module named 'pyfos.pyfos_brocade_fibrechannel'` on playbook run. 

Manual python3 test shows that the pyfos module is correctly found, and pyfos_auth gets imported succesfully, it's just the pyfos_brocade_fibrechannel that breaks:

```
Python 3.4.3 (default, Nov 12 2018, 22:25:49) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfos.pyfos_auth as pyfos_auth
>>> import pyfos.pyfos_brocade_fibrechannel as pyfos_switchfcport
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pyfos.pyfos_brocade_fibrechannel'
>>> import pyfos.pyfos_util as pyfos_util
>>> 
```

As far as I can see in the PyFOS repo, no such module seems to exist there, so while the error is correct, I cannot help but wonder why all the library functions here import it, then, and how this is supposed to work :-) Was this tested against an older version of PyFOS that did have that import?

**Comment by meersjo** [comment]
Ah, apparently that file was deleted in commit ade0ca2 there. I'll test with PyFOS 1.1 instead; I take it the code here will need reworking?

**Comment by meersjo** [comment]
Confirm that installing PyFOS 1.1 fixed the issue; however, my switches are running an unsupported FOS version, so I'm stuck anyway :-D

**Comment by daniel-chung-broadcom** [comment]
newly updated ansible modules and playbooks do not require pyfos library. Please give it a try.
