### ISSUE TITLE
Feature Request: add password-cfg to security facts

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#51]
Can you please add the password-cfg properties to the facts? I need it for regular security configuration auditing.

**Comment by daniel-chung-broadcom** [comment]
can you please check out password_cfg branch? Please also note that brocade_chassis got changed to brocade_chassis_chassis for facts gathering for defining gather_subset.

Do you just need to facts gathering portion? No need for update for the moment, right?

**Comment by mamoep** [comment]
Thank you for the quick implementation. The branch works fine!

Updates would be nice too, but are not my focus currently.

**Comment by daniel-chung-broadcom** [comment]
sounds good. We'll start with read for the moment and just let me know if you are looking for set as well. We can discuss it then.

I am currently working on restructuring directory structure to allow awx to work in the master branch as well. So, I am planning on margin this change into that branch to check into the master some time this week. I'll go ahead and close this issue once that is completed.

**Comment by daniel-chung-broadcom** [comment]
merged to master & updated galaxy.
