### ISSUE TITLE
find_ns_by_pwwn.yml playbook error

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#53]
Hello, Is find_ns_by_pwwn.yml modules got updated?  Few weeks back I used "is not defined" as well in the find_ns_by_pwwn.yml playbook to verify host wwpn's not logged into the switches to perform un-zoning after the server is powered off during the decommission process and it worked fine. But when I am using the same syntax today it's showing the below error. Can you please check and let me know if I can use "is not defined" option as well in that playbook during the un-zoning process.

  - name: print device information matching port_name
    vars:
      port_index: "{{ ansible_facts['fibrechannel_name_server'][0]['port_index'] }}"
      port_wwn: "{{ ansible_facts['fibrechannel_name_server'][0]['port_name'] }}"
      port_speed: "{{ ansible_facts['fibrechannel_name_server'][0]['link_speed'] }}"
    debug:
      msg: device with Port WWN of "{{port_wwn}}" is found at Port Indext of "{{ port_index }}". The device's speed is "{{port_speed}}"
    **when: ansible_facts['fibrechannel_name_server'][0]['port_name'] is not defined**

**Error:**

TASK [print device information matching port_name] ******************************************************************************************************************************************
fatal: [test_switch]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to be in '/home/user2/ansible-brocade/ansible-master/tasks/test_unzonesdb2.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: print device information matching port_name\n  ^ here\n"}

PLAY RECAP **********************************************************************************************************************************************************************************
test_switch                   : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
I found this comment in the ansible documentation. It looks like you are supposed to be "undefined", not "not defined". Do you want to give it a try? If you are still having issues, I can look into it further.

tasks:
    - shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined

    - fail: msg="Bailing out. this play requires 'bar'"
      when: bar is undefined

**Comment by autocoder10** [comment]
Still getting the same error even though if I use "undefined" instead of "not defined".  It worked when I used "not defined" on 05/19.

**Comment by daniel-chung-broadcom** [comment]
I haven't used "not defined" or "undefined" syntax before. Let me give it a try and see if I am seeing anything different.

As far as I know, there has not been any changes, other than index wording changes from "-" to "_" that you are aware of.

I'll keep you posted.

**Comment by daniel-chung-broadcom** [comment]
this is little weird. All I did was changed the line

    when: ansible_facts['fibrechannel_name_server'][0]['port_name'] is defined

to

    when: ansible_facts['fibrechannel_name_server'][0]['port_name'] is not defined

And I get 

TASK [print device information matching port_name] *************************************************
skipping: [san_eng_zone_seed_san_a]

instead of error that you are seeing. When I run it with "defined", I definitely see a printout.

Do you want to send me the full playbook? I could run it and see if I am seeing something different with that as well.

**Comment by autocoder10** [comment]
I think I might have found the logic. If the host is powered of, then the associated WWPN's won't login to the  fabric and the below task won't make any sense or will not execute as it won't able to print either port index, name or speed for the powered off host. If I remove that task all together then the next task is executing successfully. 

-name: print device information matching port_name
  vars:
   port_index: "{{ ansible_facts['fibrechannel_name_server'][0]['port_index'] }}"
   port_wwn: "{{ ansible_facts['fibrechannel_name_server'][0]['port_name'] }}"
   port_speed: "{{ ansible_facts['fibrechannel_name_server'][0]['link_speed'] }}"
 debug:
   msg: device with Port WWN of "{{port_wwn}}" is found at Port Indext of "{{ port_index }}". The device's speed is "{{port_speed}}"
 **when: ansible_facts['fibrechannel_name_server'][0]['port_name'] is not defined**

Sorry for not thinking through and opening an issue for this. You can close this issue for now. Thank you.

**Comment by daniel-chung-broadcom** [comment]
ok. that makes sense. Let me know if anything else comes up.
