### ISSUE TITLE
Getting "UNREACHABLE" output while running facts.yml

### ISSUE THREAD

**Issue by storl0rd** [brocade/ansible#55]
Getting the below error, attached a copy of san-inventory and facts.yml in the zip file.
[files.zip](https://github.com/brocade/ansible/files/4933486/files.zip)

I have cloned the latest version from brocade/ansible.
The library path has been added as 

export ANSIBLE_LIBRARY=/mnt/c/Automation/ansible

ansible.cfg is under - /mnt/c/Automation/ansible

storlord@L002324:/mnt/c/Automation/ansible$ ansible-playbook -i san-inventory facts.yml 

[WARNING]: Ansible is being run in a world writable directory (/mnt/c/Automation/ansible), ignoring it as an ansible.cfg source. 
For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir        

PLAY [WDC-D1-SWA2-2] *************************************************************************************************************
TASK [gather facts] **************************************************************************************************************fatal: [WDC-D1-SWA2-2]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/storlord/.ansible/tmp/ansible-tmp-1594915761.9868488-89779943995432 `\" && echo ansible-tmp-1594915761.9868488-89779943995432=\"` echo /home/storlord/.ansible/tmp/ansible-tmp-1594915761.9868488-89779943995432 `\" ), exited with result 1, stdout output: ansible-tmp-1594915761.9868488-89779943995432=/home/storlord/.ansible/tmp/ansible-tmp-1594915761.9868488-89779943995432\n", "unreachable": true}

PLAY RECAP ***********************************************************************************************************************WDC-D1-SWA2-2              : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
Looking at the inventory and fact.yml, I don't see anything wrong.

The inventory file is there to indicate which host you are running the playbook against. Technically, it is not as interesting in our case since we are running with connection of "local" and we still have to provide an ip address separately. For example, it would be possible to run the playbook without providing inventory file by setting hosts to localhost within the playbook and just executing ansible-playbook test.yml. The downside of that would be that you cannot reuse the playbook against other IP addresses. You will notice that most things needed in playbook is set as a variable and gathered from the inventory. So, the idea is that you can execute the playbook against different FOS switches by simply pointing the playbook to different host.

Anyway, I have never seen the warning about the ansible.cfg. I think it is just saying that the directory writable by everyone. That in itself is ok. But it seems to be saying that ansible.cfg is being ignored. Can we update the directory to be writable by you only and see if the playbook executes differently?

**Comment by daniel-chung-broadcom** [comment]
btw, I did a quick experiment to convert my ansible directory to be writable by all. I got the warning as you are seeing. I got a different warning during the execution - complaining that modules cannot be found and that makes sense since ansible.cfg is ignored. Please update the ansible directory to writable by you only and execute the playbook again. We can debug further from there.

**Comment by storl0rd** [comment]
I am running ansible from Windows Subsystem for Linux, I removed the ansible.cfg from the local directory and updated the main ansible.cfg (/etc/ansible/ansible.cfg) file with the path to utils folder. I dont get the warning message anymore, but I still get the unreachable error.

 storlord@L002324:/mnt/c/Automation/ansible$ ansible-playbook -i san-inventory facts.yml 

PLAY [WDC-D1-SWA2-2] *************************************************************************************************************
TASK [gather facts] **************************************************************************************************************fatal: [WDC-D1-SWA2-2]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /home/storlord/.ansible/tmp/ansible-tmp-1594931686.6241925-185389561841789 `\" && echo ansible-tmp-1594931686.6241925-185389561841789=\"` echo /home/storlord/.ansible/tmp/ansible-tmp-1594931686.6241925-185389561841789 `\" ), exited with result 1, stdout output: ansible-tmp-1594931686.6241925-185389561841789=/home/storlord/.ansible/tmp/ansible-tmp-1594931686.6241925-185389561841789\n", "unreachable": true}

PLAY RECAP ***********************************************************************************************************************WDC-D1-SWA2-2              : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
I have never seen these errors. I don't think "unreachable" is the root cause here. From what I can tell, it is complaining about target directory permission. Can you check to see if you are able to create /home/storlorg/.ansible/tmp/xyz directory?  My understanding is that ansible creates bunch of temp files during the execution and, my best guess, is that your directory permission is not allowing it.

**Comment by storl0rd** [comment]
After much troubleshooting, I downgraded to Ubuntu 18.04 and I have made some progress, the issue that i get now is as below

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all' 

PLAY [localhost] **********************************************************************************************************************
TASK [gather facts] *******************************************************************************************************************fatal: [localhost]: FAILED! => {"changed": false, "lxml_err_msg": "The brocade_xml module requires the xmltodict python library installed on the managed machine", "msg": "API failed to return switch firmware version"}

PLAY RECAP ****************************************************************************************************************************localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


I have verified that on my local machine xmltodict is installed - xmltodict==0.12.0

**Comment by daniel-chung-broadcom** [comment]
it looks like the module is being loaded and wanting to execute. so, that's great progress.

I am not sure why xmltodict is not being seen. The only thing we do in utils/brocade_xml.py is

try:
  import xmltodict

So, there isn't much wiggle room here. I am not entirely sure why ansible isn't picking up the xmltodict.

can you try

ansible-playbook --version

This should tell you which python version is being picked up. One thing that we can try is to install the xmltodict for that specific python version. I have seen in previous attempts that a library is installed for one version of python specifically. Not sure if this is your issue but something that we can look at.

**Comment by storl0rd** [comment]
**I restarted my session and now I get a different error.**

storlord@L002324:~/ansdev$ export ANSIBLE_LIBRARY="/mnt/c/Automation/ansible/library"                                                  

storlord@L002324:~/ansdev$ ansible-playbook facts.yml
 [WARNING] Ansible is being run in a world writable directory (/home/storlord/ansdev), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all' 

PLAY [localhost] **********************************************************************************************************************
TASK [gather facts] *******************************************************************************************************************fatal: [localhost]: FAILED! => {"msg": "Could not find imported module support code for brocade_facts.  Looked for either exit_after_login.py or brocade_connection.py"}

PLAY RECAP ****************************************************************************************************************************localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Here is the ansible.cfg file content**
module_utils   = /mnt/c/Automation/ansible/utils
interpreter_python = auto

**Comment by daniel-chung-broadcom** [comment]
it looks like you went back to ignoring the ansible.cfg. I think that is because /home/storlord/ansdev directory is writable by everyone.

**Comment by daniel-chung-broadcom** [comment]
getting back to xmltodict. Once you figured out python version, you can go ahead and run it and within it, you can try "import xmltodict". If xmltodict was installed for the right version of python that is being picked up by ansible, it should not error.

**Comment by storl0rd** [comment]
Sorry, yes I just noticed that - and I also see that ansible is using python 2.7 . I seem to have both versions of python installed , xmltodict is installed in Python 3 .

**Comment by daniel-chung-broadcom** [comment]
Can you try getting into the interactive mode for python2.7 and see if you can import xmltodict?

**Comment by daniel-chung-broadcom** [comment]
Is it possible to remove writable option for the directory where you are executing the playbooks?

**Comment by daniel-chung-broadcom** [comment]
I meant writable option for other and group

**Comment by storl0rd** [comment]
I changed the permission, and did a installed xmltodict for python2 and finally everything looks to be working. 

Successfully ran the playbook. 
PLAY RECAP ****************************************************************************************************************************localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Thank you for your help.

**Comment by daniel-chung-broadcom** [comment]
great. Let me know if anything else comes up or request for modules/playbooks.
