### ISSUE TITLE
Feature Request: add brocade-media and brocade-fibrechannel-trunk facts

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#57]
Please add brocade-media and brocade-fibrechannel-trunk information to the facts. I need it for daily configuration checks.

**Comment by daniel-chung-broadcom** [comment]
Let me look into them. I'll keep you posted.

**Comment by daniel-chung-broadcom** [comment]
Can you try out.

additional_facts

branch? I have a fix for the speed/max_speed there as well.

Unfortunately, I don't have trunk setup handy. So, just verified the media for the moment. While I acquire a system with trunk setup, I was think that you want to give it a try instead of waiting.

**Comment by mamoep** [comment]
The branch works fine. I cannot test _brocade_fibrechannel_trunk_trunk_area_ but everything else looks good. Thank you for the quick reaction!

**Comment by daniel-chung-broadcom** [comment]
merged to master. closing.
