### ISSUE TITLE
brocade_interface_fibrechannel Facts: Speed / Max_Speed inconsistent format

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#58]
The properties _speed_ and _max_speed_ in brocade_interface_fibrechannel facts use different formats.

```
"speed": "16Gig"
"max_speed": "32000000000"
```

For consistency and comparability I would expect both use the same format.

**Comment by daniel-chung-broadcom** [comment]
Let me look into it. I think I made one to be interpreted from underlying rest data, while leaving the other. Let me see if I can reconcile those to be the same.

**Comment by mamoep** [comment]
Fix is working in additional_facts branch!

**Comment by daniel-chung-broadcom** [comment]
merged to master. closing.
