### ISSUE TITLE
Switch name and portname

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#62]
Hello, we have a core-edge switch setup and storage ports are patched to cores and all host ports are patched to edge switches. Currently after we perform zoning or un-zoning from the cores, we login into edge switches and run the portname cmd to add host name to the ports where host WWPN is logged into. So, I am checking to see if we can get the switch name where that host WWPN is logged in as well using "find_ns_by_pwwn.yml" ?  

**find_ns_by_pwwn.yml**
- name: gather device info
    brocade_list_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade-name-server"
      list_name: "fibrechannel-name-server"
      attributes:
        port_name: "{{wwn_to_search}}"

- name: print device information matching port_name
   vars:
     port_index: "{{ ansible_facts['fibrechannel_name_server'][0]['port_index'] }}"
     port_wwn: "{{ ansible_facts['fibrechannel_name_server'][0]['port_name'] }}"
     port_speed: "{{ ansible_facts['fibrechannel_name_server'][0]['link_speed'] }}"
   debug:
     msg: device with Port WWN of "{{port_wwn}}" is found at Port Indext of "{{ port_index }}". The device's speed is "{{port_speed}}"
   when: ansible_facts['fibrechannel_name_server'][0]['port_name'] is defined

Also, Is there any module that I can use to run "portname" command to add the name to the switch port.

portname -i  <port_index> -n "<name>"

**Comment by daniel-chung-broadcom** [comment]
portname command maps to fibrechannel object's user-friendly-name. I just uploaded portname.yml on supportsave branch. Please take a look and see that is what you are looking for.

**Comment by daniel-chung-broadcom** [comment]
as for getting switch name from the NS entry, let me find out.

**Comment by daniel-chung-broadcom** [comment]
it looks like we could potentially go from ns.pid -> domain id -> get switch from brocade-fabric/fabric-switch with matching domain id -> fabric-switch's wwn. I am not finding an easy way to parse hex pid to domain id for the moment. Please let me know if you find a way parse that info. I'll keep you posted on my research.

**Comment by daniel-chung-broadcom** [comment]
I think regex might be too complicated. I am thinking of just adding an module that returns the fabric-switch based on the device's PID. find_ns_by_pwwn.py would now return the switch information at the end. Would this be sufficient - along with the portname.yml example - to help you create a playbook that you need?

dc400196@iaas-l-2206-611:~/ansible$ ansible-playbook -i testinventory find_ns_by_pwwn.yml 

PLAY [san_eng_zone_seed_san_a] *************************************************

TASK [gather device info] ******************************************************
ok: [san_eng_zone_seed_san_a]

TASK [print device information matching port_name] *****************************
ok: [san_eng_zone_seed_san_a] => {
    "msg": "device with Port WWN of \"10:00:00:10:9b:22:ec:3d\" is found at Port Indext of \"5\". The device's speed is \"32G\""
}

TASK [gather device alias info] ************************************************
ok: [san_eng_zone_seed_san_a]

TASK [print device alias information matching port_name] ***********************
skipping: [san_eng_zone_seed_san_a]

TASK [find switch with the matching domain id] *********************************
ok: [san_eng_zone_seed_san_a]

TASK [print switch WWN where the device is connected] **************************
ok: [san_eng_zone_seed_san_a] => {
    "msg": "The device's is connected at \"10:00:d8:1f:cc:03:3d:e0\""
}

PLAY RECAP *********************************************************************
san_eng_zone_seed_san_a    : ok=5    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
After reading through the description couple of times, I am still not clear on what is the sequence events you want to happen. Little confused as to how switch name is related to host pwwn and what will be assigned using portname. Do you mind providing what is the original input that you want to start with and what configuration changes you want to result from? Thanks.

**Comment by autocoder10** [comment]
The portname.yml works great. Here is the process we are doing manually for both zoning and un-zoning and want to automate it.

Steps for Zoning: (Similar process for un-zoning as well)
1. Host WWPN's are patched to edge switches on both fabric A and fabric B.
2. Perform zoning on the core switches between Host WWPN's and Storage ports on both fabrics.
3. once zoning is completed on the core switches, we will login into edge switches and rename the ports where the Host WWPN's are logged into with "portname" cmd for reporting and quick troubleshooting purpose.

So to automate Step#3, we need edge switches name to login and run the portname.yml playbook you provided. As you mentioned it's little bit complicated to get the edge switch name from Pid but trying to see if there is any other way to get the edge switch names.

**Comment by daniel-chung-broadcom** [comment]
Thanks for the info. 

When you say switch name, what does that translate to? In my example, I was printing the WWN of the switch. Are you looking for the string name of the switch?

Is printing the switch name sufficient for your usage - similar to what I had shown earlier in this thread?

For example:

TASK [print switch WWN where the device is connected] **************************
ok: [san_eng_zone_seed_san_a] => {
"msg": "The device's is connected at "10:00:d8:1f:cc:03:3d:e0" "cassisan_073_020"
}

**Comment by autocoder10** [comment]
Sorry for the confusion. The switch name I am referring to is the string name assigned to that switch that will display after we login and also can get it with the "switchname" cmd.

**Comment by daniel-chung-broadcom** [comment]
Just push the changes. Please check out the v9.0.0a branch for the updated playbook and see if this satisfy your requirements.

**Comment by autocoder10** [comment]
I ran the playbook with updated modules from  v9.0.0a branch and seeing this error...

TASK [find switch with the matching domain id] **********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: login() takes 6 positional arguments but 7 were given
fatal: [testswitch]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/testuser/.ansible/tmp/ansible-tmp-1596732835.98-8801-33078586702882/AnsiballZ_brocade_fabric_switch_facts_by_pid.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/testuser/.ansible/tmp/ansible-tmp-1596732835.98-8801-33078586702882/AnsiballZ_brocade_fabric_switch_facts_by_pid.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/testuser/.ansible/tmp/ansible-tmp-1596732835.98-8801-33078586702882/AnsiballZ_brocade_fabric_switch_facts_by_pid.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.brocade_fabric_switch_facts_by_pid', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_brocade_fabric_switch_facts_by_pid_payload_fv70u6k0/ansible_brocade_fabric_switch_facts_by_pid_payload.zip/ansible/modules/brocade_fabric_switch_facts_by_pid.py\", line 184, in <module>\n  File \"/tmp/ansible_brocade_fabric_switch_facts_by_pid_payload_fv70u6k0/ansible_brocade_fabric_switch_facts_by_pid_payload.zip/ansible/modules/brocade_fabric_switch_facts_by_pid.py\", line 137, in main\nTypeError: login() takes 6 positional arguments but 7 were given\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by daniel-chung-broadcom** [comment]
do you have a private copy of utils/brocade_connection.py by any chance? Looking at the github.com copy of v9.0.0a copy, I see that login does take 7 inputs. 

def login(fos_ip_addr, fos_user_name, fos_password, is_https, throttle, result, timeout):

**Comment by autocoder10** [comment]
I think you are correct.  Now I got what I am looking for. Really appreciate your help.

**Comment by daniel-chung-broadcom** [comment]
Great. I'll hold unto these changes until I am ready to merge to master with other accumulated changes. And close the issue once merged. Please let me know if you need anything else for this use case.

**Comment by autocoder10** [comment]
Sure, Thanks.

**Comment by daniel-chung-broadcom** [comment]
merged to main and galaxy.ansible.com. closing.
