### ISSUE TITLE
Bad Request when using brocade_interface_fibrechannel

### ISSUE THREAD

**Issue by mgoetze5** [brocade/ansible#64]
In an environment where other modules are working fine, I'm getting an error trying to run this rather simple task:

  - name: E-Ports fcsw-gts-a1
    brocade_interface_fibrechannel:
      credential: "{{credential}}"
      vfid: -1
      ports:
        - name: "0/0"
          user_friendly_name: "ISL fcsw-gts-a2 via GTS3 2319 <-> GTS4 3314"
        - name: "0/1"
          user_friendly_name: "ISL fcsw-gts-a2 via GTS3 2319 <-> GTS4 3314"

The error is:

fatal: [fcsw-gts-a1]: FAILED! => {"PATCH_resp_code": 400, "PATCH_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "16715778", "error-module": "cal"}, "error-message": "StartTag: invalid element name", "error-path": "/rest/running/brocade-interface/fibrechannel", "error-tag": "operation-failed", "error-type": "application"}}}, "PATCH_resp_reason": "Bad Request", "PATCH_url": "https://********/rest/running/brocade-interface/fibrechannel", "add_entries": [], "add_retcode": 0, "changed": false, "current_entries":

followed by a complete dump of my current port configuration. The switch in question is a 6510 running 8.2.2a.

**Comment by daniel-chung-broadcom** [comment]
I am also able to repro the problem on my end. I'll take a look and see what is going on. I'll keep you posted.

**Comment by daniel-chung-broadcom** [comment]
it looks like < in the name was being interpreted by xml parser. I added code to replace < with &lt; in the string before sending to FOS and that seems to allow me to set the port name to the exact string that you specified. I pushed the changes to v9.0.0a branch. Can you please try out the change on that branch?

**Comment by mgoetze5** [comment]
Looks good, thanks!

**Comment by daniel-chung-broadcom** [comment]
Great. I'll hold unto these changes until I do a merge into master along with other accumulate changes. I'll go ahead and close the issue once these changes are merged to master & added galaxy.ansible.com.

**Comment by daniel-chung-broadcom** [comment]
merged to main and galaxy.ansible.com. Closing.
