### ISSUE TITLE
Feature Request: SSH key distribution

### ISSUE THREAD

**Issue by mgoetze5** [brocade/ansible#65]
I would love to be able to distribute authorized SSH keys for users on the switch via ansible.

**Comment by daniel-chung-broadcom** [comment]
Do you mind clarifying what you mean by this? Some examples of the specific steps would be very helpful. Thanks

**Comment by mgoetze5** [comment]
CLI equivalent: sshutil importpubkey

**Comment by daniel-chung-broadcom** [comment]
I believe that maps to brocade-security/sshutil-public-key-action object in FOS REST. I am looking to confirm. I'll keep you posted on module/playbook based on what I find out.

**Comment by daniel-chung-broadcom** [comment]
Can you please check out

facts_sshutil_public_key.yml
sshutil_public_key_import.yml
sshutil_public_key_delete.yml

on v9.0.0v and see if these are what you are looking for?

**Comment by mgoetze5** [comment]
I had a glance at the REST API reference, it seems like sshutil-public-key-action lets you have the switch download the key from somewhere (as was unfortunately necessary in the CLI method) but there's also sshutil-public-key* where you can just write the public key directly, that would be what I want.

**Comment by mgoetze5** [comment]
...though on second glance that field is marked as ro, so the extra hoop of having the SSH key available for download somewhere would still be necessary. It really shouldn't be, perhaps you can pass that on as a feature request to the API developers.

**Comment by daniel-chung-broadcom** [comment]
Sure. I believe sshutil-public-key list is for display or delete. I have covered those actions with facts & delete playbooks.

I'll pass along the suggestion. 

Please let me know if the new playbooks satisfy your use case in the meanwhile.

**Comment by mgoetze5** [comment]
When I did this by hand I would rely on SSH Agent forwarding to authenticate to the server I was pulling the keys from, that's not an option with ansible, so I'll have to set up something where I'm comfortable sending the password along. I'll get back to you within a week.

**Comment by daniel-chung-broadcom** [comment]
just so I understand completely, I think when you say "sending the password along", I think you are referring to user_password specified in the playbook being sent to FOS over FOS REST API, right? I think one option would be to use HTTPS as a connection between Ansible and FOS.

Also, although user_password is a clear text in the playbook, it does get base64 encoded by the utils/brocade_objects.py module when sent to FOS. Base64 doesn't really offer much, if any, security. But just wanted to share for completeness' sake.

**Comment by daniel-chung-broadcom** [comment]
Any additional comments on the topic? The playbooks that I mentioned are merged to main and forwarded your inputs. Thanks.

**Comment by mgoetze5** [comment]
Sorry, the heat has been impinging on my productivity and ansible-vault isn't doing what I want it to. The modules do work, but it's unfortunate that they're not idempotent, and I would still love a way to just push the keys rather than tell the switch where to pull them. That said, they do accomplish what I need, thanks!

**Comment by daniel-chung-broadcom** [comment]
I'll plan to close this issue based on the merge and forwarding of the inputs. Please let me know if you feel otherwise. Thanks.

**Comment by mgoetze5** [comment]
Sure, no need for you to keep an open issue around for something not currently supported in the API.

**Comment by daniel-chung-broadcom** [comment]
closing.
