### ISSUE TITLE
ag-mode 3 not recognized

### ISSUE THREAD

**Issue by barcveg** [brocade/ansible#68]
REST API Guide for v8.2.x says there are three valid values for fibrechannel-switch/ag-mode: 0,1,3
utils/brocade_fibrechannel_switch.py only supports 0 and 1

result: when getting facts for an ag-mode enabled switch, the rest query returns 3 (supported and enabled) but the ansible module  returns "ag_mode": false

**Comment by daniel-chung-broadcom** [comment]
Let me look into the issue and get back to you.

**Comment by daniel-chung-broadcom** [comment]
it looks like I was erroneously converting the ag-mode to a boolean variable. Can you please take a look at

user_config_password

branch and see if the change reflects that you are expecting?

Thanks

**Comment by daniel-chung-broadcom** [comment]
Did you get a chance to take a look at the change? The change is now merged to ag_configuration branch being prep'ed for the merge to master in few weeks. Please let me know if any issues. Thanks.

**Comment by barcveg** [comment]
I could only test it with AG capable devices.
Reading the ag_mode setting and changing it between 1 and 3 works.

Your example playbook (ag_enable.yml) failed in my environment with factory setting switch as the Switch Authentication Policy is set to passive by default and it has to be off for activating the AG mode. I couldn't find that through the REST API on FOS 8.2 so I had to change the setting via CLI before successfully running the playbook.

`TASK [ag mode enabled. if changing, switch will reboot afterward.] ****************************
fatal: [accessgateway]: FAILED! => {"PATCH_resp_code": 400, "PATCH_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "-53", "error-module": "access-gateway"}, "error-message": "ERROR: Authentication policies are enabled in the switch. Please disable the Authentication policies", "error-path": "/fibrechannel-switch/name/<switchwwn>/ag-mode", "error-tag": "Operation-failed", "error-type": "protocol"}}}`

**Comment by barcveg** [comment]
I agree close the issue when the branch is merged. Thanks.

**Comment by daniel-chung-broadcom** [comment]
changed merged to master and published on galaxy. closing.
