### ISSUE TITLE
Question: Howto use brocade_list_obj for ldap role mapping

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#69]
I tried to use brocade_list_obj module to configure brocade-security/ldap-role-map but it failed. Do I use it wrong?
FOS 8.2.1 is in use.

My playbook:
```` -hosts: localhost
  become: false
  gather_facts: false
  collections:
    - brocade.fos
  name: Brocade LDAP Role
  vars:
    #group name in AD to be mapped
    ldap_role: ROLE_NAME_REDACTED
  vars_prompt:
  - name: username
    prompt: "Enter username to connect to the switch!"
    private: no
    default: "{{ lookup('env','USER') }}"
  - name: password
    prompt: "Enter password for to connect to the switch!"
  tasks:
  - name: ldap role mapping
    brocade_list_obj:
      credential:
        fos_ip_addr: "{{ item }}"
        fos_user_name: "{{ username }}"
        fos_password: "{{ password }}"
        https: true
      vfid: -1
      all_entries: false
      module_name: "brocade-security"
      list_name: "ldap-role-map"
      entries:
        - ldap_role: "{{ ldap_role }}"
          switch_role: admin
    with_items: "{{ groups['SAN_Switch_Test'] }}"
````

Output:
````failed: [localhost] (item=item_redacted) => {"PATCH_resp_code": 400, "PATCH_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "589824", "error-module": "cal"}, "error-message": "No settable data", "error-path": "/rest/running/brocade-security/ldap-role-map", "error-tag": "operation-failed", "error-type": "application"}}}, "PATCH_resp_reason": "Bad Request", "PATCH_url": "https://********/rest/running/brocade-security/ldap-role-map", "add_entries": [], "add_retcode": 0, "ansible_loop_var": "item", "changed": false, "current_entries": [{"chassis_access_role": null, "home_virtual_fabric": "0", "ldap_role": "EXISITNG_ROLE_NAME_REDACTED", "switch_role": "admin"}, {"chassis_access_role": null, "home_virtual_fabric": "0", "ldap_role": "ROLE_NAME_REDACTED", "switch_role": "admin"}], "delete_entries": [], "delete_retcode": 0, "diff_entries": [{"ldap-role": "ROLE_NAME_REDACTED"}, {"ldap-role": "ROLE_NAME_REDACTED"}], "diff_retcode": 0, "item": "item_redacted", "msg": "PATCH failed", "patch_str": "<ldap-role-map><ldap-role>ROLE_NAME_REDACTED</ldap-role></ldap-role-map><ldap-role-map><ldap-role>ROLE_NAME_REDACTED</ldap-role></ldap-role-map>", "response": {"Response": {"ldap-role-map": [{"chassis_access_role": null, "home_virtual_fabric": "0", "ldap_role": "GE_Storage-SAN_OS", "switch_role": "admin"}, {"chassis_access_role": null, "home_virtual_fabric": "0", "ldap_role": "ROLE_NAME_REDACTED", "switch_role": "admin"}]}}}````

**Comment by daniel-chung-broadcom** [comment]
I haven't tried this myself. Let me give it a try and see what I get myself. I'll keep you posted.

**Comment by daniel-chung-broadcom** [comment]
I am not sure what is going on here but I am not getting an error in this case. Here is what my task section looks like. Do you mind running your play with -vvvv option and see if the verbose mode would give us bit more clue on what is going on? patch_str doesn't look right, where dlap-role-map is specified twice. Maybe it is related to with_items? 

- name: ldap
  brocade_list_obj:
    credential: "{{credential}}"
    vfid: -1
    all_entries: false
    module_name: "brocade-security"
    list_name: "ldap-role-map"
    entries:
       - ldap_role: ROLE_NAME_REDACTED
       - switch_role: admin

**Comment by mamoep** [comment]
Your entries section differ from mine. You added a hyphen before switch_role. From the examples I thought that a hyphen will start a single entry and the lines without hyphens describe further attributes of that entry. Is that correct?

I wanted to the replicate the following CLI command: `ldapcfg --maprole ldaprole switchrole`

**Comment by daniel-chung-broadcom** [comment]
I am sorry but that was typo. It has it correct in my playbook

- ldap_role: xxx
  switch_role:

to indicate that it is one entry in an array. My copy and paste didn't work and I had to manually type in the playbook and I erred.

Please send me your -vvvv output. If you can tell me what is in the "groups" inventory, I think that would be helpful. I am wondering if the loop is causing logic that the module isn't expecting.

**Comment by mamoep** [comment]
The variable _groups['SAN_Switch_Test']_ catches all members of that group from inventory. I always use this syntax to loop through all my switches. If you have a more elegant way to loop through the inventory I am very willing to learn. Anyway this never caused any issues. I also tried to do it without the loop, but the issue stays the same. I am running this on RHEL 7.8.

Here is the verbose output.
````
ansible-playbook 2.9.10
  config file = /ansible/private/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /ansible/private/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /ansible/private/inventory as it did not pass its verify_file() method
script declined parsing /ansible/private/inventory as it did not pass its verify_file() method
auto declined parsing /ansible/private/inventory as it did not pass its verify_file() method
Parsed /ansible/private/inventory inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: brocade_ldap_role_mapping.yml ***********************************************************************************************************************************************************************
Positional arguments: playbooks/brocade_ldap_role_mapping.yml
become_method: sudo
inventory: (u'/ansible/private/inventory',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
become: True
1 plays in playbooks/brocade_ldap_role_mapping.yml
Enter username to connect to the switch! [userw]:
Enter password for to connect to the switch!:

PLAY [Brocade LDAP Role Mapping] ******************************************************************************************************************************************************************************
META: ran handlers

TASK [ldap role mapping] **************************************************************************************************************************************************************************************
task path: /ansible/private/playbooks/brocade_ldap_role_mapping.yml:21
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user
<127.0.0.1> EXEC /bin/sh -c 'echo ~user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir /home/user/.ansible/tmp/ansible-tmp-1599063763.4-15604-48305434645085 && echo ansible-tmp-1599063763.4-15604-48305434645085="` echo /home/user/.ansible/tmp/ansible-tmp-1599063763.4-15604-48305434645085 `" ) && sleep 0'
Using module file /home/user/.ansible/collections/ansible_collections/brocade/fos/plugins/modules/brocade_list_obj.py
<127.0.0.1> PUT /home/user/.ansible/tmp/ansible-local-155208xyZOf/tmpTYeiSm TO /home/user/.ansible/tmp/ansible-tmp-1599063763.4-15604-48305434645085/AnsiballZ_brocade_list_obj.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1599063763.4-15604-48305434645085/ /home/user/.ansible/tmp/ansible-tmp-1599063763.4-15604-48305434645085/AnsiballZ_brocade_list_obj.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/user/.ansible/tmp/ansible-tmp-1599063763.4-15604-48305434645085/AnsiballZ_brocade_list_obj.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1599063763.4-15604-48305434645085/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "PATCH_resp_code": 400,
    "PATCH_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf",
            "error": {
                "error-app-tag": "Error",
                "error-info": {
                    "error-code": "589824",
                    "error-module": "cal"
                },
                "error-message": "No settable data",
                "error-path": "/rest/running/brocade-security/ldap-role-map",
                "error-tag": "operation-failed",
                "error-type": "application"
            }
        }
    },
    "PATCH_resp_reason": "Bad Request",
    "PATCH_url": "https://********/rest/running/brocade-security/ldap-role-map",
    "add_entries": [],
    "add_retcode": 0,
    "changed": false,
    "current_entries": [
        {
            "chassis_access_role": null,
            "home_virtual_fabric": "0",
            "ldap_role": "ROLE1",
            "switch_role": "admin"
        }
    ],
    "delete_entries": [],
    "delete_retcode": 0,
    "diff_entries": [
        {
            "ldap-role": "ROLE2"
        }
    ],
    "diff_retcode": 0,
    "invocation": {
        "module_args": {
            "all_entries": false,
            "credential": {
                "fos_ip_addr": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "fos_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "fos_user_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "https": true
            },
            "entries": [
                {
                    "ldap_role": "ROLE2",
                    "switch_role": "admin"
                }
            ],
            "list_name": "ldap-role-map",
            "module_name": "brocade-security",
            "throttle": null,
            "timeout": null,
            "vfid": -1
        }
    },
    "msg": "PATCH failed",
    "patch_str": "<ldap-role-map><ldap-role>ROLE2</ldap-role></ldap-role-map>",
    "response": {
        "Response": {
            "ldap-role-map": {
                "chassis_access_role": null,
                "home_virtual_fabric": "0",
                "ldap_role": "ROLE1",
                "switch_role": "admin"
            }
        }
    }
}

PLAY RECAP ****************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
````

**Comment by daniel-chung-broadcom** [comment]
I found the issue. Since this a new object being handled, I didn't have the key identified in the list_keys structure within utils/brocade_objects.py. And my test case worked because I only had one entry without overlapping switch_roles. I added "ldap_role" as a key for "ldap_role_map" in the list_keys structure and it seems to be working fine. I also added brocade_security_ldap_role_map module. In this case, the module expects full list. So, it will add/update/delete based on the full list. You can take a look at ldap_role_map.yml for reference. brocade_list_obj should also work as well since the list_keys is used by both code flows. Please check out ag_configuration branch and let me know if this works.

Thanks.

**Comment by mamoep** [comment]
The branch works with brocade_list_obj. I thought this was meant to be used for generic use cases. If you have to update your list_keys everytime someone comes up with a new use case, it will give users a hard time.
Maybe you could also add support for ldap-server & auth-spec, then the ldap features would be complete.

**Comment by daniel-chung-broadcom** [comment]
good point. I think I'll add all known object/key pairs to cover generic cases. As before, I'll hold onto the change/issue until merged to master. Thanks.

**Comment by daniel-chung-broadcom** [comment]
fyi. just updated the branch with the full list of known objects & keys.

**Comment by daniel-chung-broadcom** [comment]
fyi. I'll plan to close this issue when ag_configuration branch is merged to master. Please let me know if there is anything else that we need to follow up in regards to this thread.

**Comment by daniel-chung-broadcom** [comment]
changed merged to master and published on galaxy. closing.
