### ISSUE TITLE
Brocade switch ping issue

### ISSUE THREAD

**Issue by srini1988** [brocade/ansible#72]
When trying to ping the SAN switch receiving the following error
**Error**
```
>  "msg": "failed to resolve remote temporary directory from ansible-tmp-1600196023.86-6712-80288639012102: `( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir ~/.ansible/tmp/ansible-tmp-1600196023.86-6712-80288639012102 && echo ansible-tmp-1600196023.86-6712-80288639012102=\"` echo ~/.ansible/tmp/ansible-tmp-1600196023.86-6712-80288639012102 `\" )` returned empty string"
```
```
Ansible --version
ansible 2.9.10
  config file = /home/playbooks/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 27 2019, 09:57:45) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]
```

**Comment by daniel-chung-broadcom** [comment]
Do you mean ansible ping module? Are you able to share the playbook for me to try exactly what you are trying?

**Comment by srini1988** [comment]
Below issue I am facing, correct me if I am wrong 

`[root@Servera playbooks]# cat inventory`
`<IP address>    ansible_ssh_user=<username>  ansible_ssh_pass=<Password>`

`[root@Servera playbooks]# ansible all -m ping`
`<IP address> | FAILED! => {
    "msg": "failed to resolve remote temporary directory from ansible-tmp-1600361593.29-14031-74994783488408: `( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir ~/.ansible/tmp/ansible-tmp-1600361593.29-14031-74994783488408 && echo ansible-tmp-1600361593.29-14031-74994783488408=\"` echo ~/.ansible/tmp/ansible-tmp-1600361593.29-14031-74994783488408 `\" )` returned empty string"
}`

`[root@Servera playbooks]# ansible --version`
`ansible 2.9.10
  config file = /home/playbooks/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 27 2019, 09:57:45) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]`
`[root@Servera playbooks]#`

`[root@servera playbooks]# ansible all --list-hosts`
 ` hosts (1):
    <IP address>
[root@servera playbooks]#`

**Comment by daniel-chung-broadcom** [comment]
fyi. I am still looking into how ping works. The weird thing is that the ip address being ping aren't the ones listed in the inventory file. But I am not getting any errors. I'll keep you posted on what I find out.

dc400196@iaas-l-2206-611:~/ansible$ ansible all -m ping
yy.yy.yy.yy | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
xx.xx.xx.xx | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

**Comment by daniel-chung-broadcom** [comment]
a quick update. I don't seem to have any issues with ping when I added fos switch ip in the /etc/ansible/hosts file.

Here is the format that I used.

xx.xx.xx.xx ansible_ssh_user=admin ansible_ssh_password=fibranne

--list_hosts shows me the ip address fine as well.

**Comment by srini1988** [comment]
Will Python 2.7.5 version support?
```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  **python version = 2.7.5 (default, Nov 27 2019, 09:57:45) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]**
```
```
Appl     Primary/Secondary Versions
------------------------------------------
FOS      v8.2.2c
         v8.2.2c
```

**Comment by daniel-chung-broadcom** [comment]
Great. Thanks for the update.

**Comment by tcspivey** [comment]
I have reviewed this and various other posts but am still having the issue after following the wiki setup.

$ ansible-playbook facts.yml -u admin

PLAY [x.x.x.x] ***********************************************************************************************************************************************************************************************************************

TASK [gather facts] ***********************************************************************************************************************************************************************************************************************
fatal: [x.x.x.x]: FAILED! => {"msg": "failed to resolve remote temporary directory from ansible-tmp-1630605357.991134-166049661343707: `( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1630605357.991134-166049661343707 `\" && echo ansible-tmp-1630605357.991134-166049661343707=\"` echo ~/.ansible/tmp/ansible-tmp-1630605357.991134-166049661343707 `\" )` returned empty string"}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************
x.x.x.x               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

$ ansible --version
ansible 2.9.4
  config file = /restapi/san/ansible.cfg
  configured module search path = ['/restapi/san/ansible/library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Comment by daniel-chung-broadcom** [comment]
any particular reason why you are specifying -u option? I also use -i option to indicate inventory information in regards to the FOS switch that I am connecting to.

**Comment by tcspivey** [comment]
Without the -u option I receive this error:
UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).", "unreachable": true}

With the -u I receive the ‘remote temporary directory’ error.

The vars: section is below that I am using:
  vars:
    credential:
      fos_ip_addr: 'x.x.x.x'
      fos_user_name: 'admin'
      fos_password: '~~~'
      https: self

**Comment by daniel-chung-broadcom** [comment]
I usually run my script as something like

ansible-playbook -i san-inventory facts.yml

where do you specify that the host being used for the playbook is using local for ansible_connection?

**Comment by tcspivey** [comment]
Thank you!  I knew I was missing something simple.  I had the switch defined in the ‘-hosts’ section of the playbook instead of localhost.

It’s working now.

**Comment by daniel-chung-broadcom** [comment]
Great. glad to have helped.

**Comment by tcspivey** [comment]
Quick question.  If have general questions regarding the ansible integration or PyFOS should I contact support or is there a ‘better’ way to ask?

**Comment by daniel-chung-broadcom** [comment]
content within the repo is available as open source. So, I think the best way is probably to file an issue.
