### ISSUE TITLE
Performing configupload using ansible modul

### ISSUE THREAD

**Issue by munokar** [brocade/ansible#82]
Hi,

is it possible to perform a confgupload via ansible?
Would be nice to have the same featureset as with supportsave.

Thanks for the feedback

**Comment by daniel-chung-broadcom** [comment]
Not currently. However, I believe that the support of configupload/download is being considered for future fos and when it becomes available in FOS, we can implement the ansible modules to support it at that time.

**Comment by daniel-chung-broadcom** [comment]
closing based on the latest answer. Please reopen with comment if additional information is needed. Thanks.

**Comment by babulap-pare** [comment]
Thanks Balaji, I am very new to Ansible  ( using Ansible Automation Platform Controller 4.5.0 ). I want to know how can i use it. I understood that i have to update the login credential of SAN switch in the yml file however I did not see any option to update the SFTP server details and to specify the port number. I also want to know how i can i identify which other files in the repo works in association with the configupload.yml(https://github.com/brocade/ansible/blob/master/configupload.yml)
