### ISSUE TITLE
Brocade Module Parameters

### ISSUE THREAD

**Issue by ta-osan** [brocade/ansible#84]
Hi,

Where is the documentation that supports the Brocade modules please? The example playbooks provide limited information regrading parameter support, or do the example playbooks outline all of the available parameters and the modules don't support the full range of options? For example:

  - name: fabric configuration
    brocade_fibrechannel_configuration_fabric:
      credential: "{{credential}}"
      vfid: -1
      fabric:
        insistent_domain_id_enabled: True
        in_order_delivery_enabled: False
        fabric_principal_enabled: True
        fabric_principal_priority: "0x3"
    register: result

Does this module also support all parameters found under the 'configure' command, e.g. R_A_TOV, Sequence Level Switching, etc? If yes, what format do the Ansible parameters take?

Thanks

**Comment by daniel-chung-broadcom** [comment]
Other than the specific attributes are mentioned to be using SSH as the underlying mechanism (these are documented in the readme portion), all other attributes supported for a given module would be mapped to the underlying REST implementation. The rest implementation is documented in the yang modeling. These models are available under 

https://github.com/brocade/yang

For example, you can find "fabric" object under https://github.com/brocade/yang/blob/master/8.2.2/8.2.2c/brocade-fibrechannel-configuration.yang. And you can find attributes that belong to the fabric object. In case of 8.2.2, the only attribute under the fabric object is

      leaf insistent-domain-id-enabled {

Hope this clarifies. Please let me know if you have additional questions.

**Comment by daniel-chung-broadcom** [comment]
closing since the answer has been provided. Please reopen if additional questions.
