### ISSUE TITLE
Add module brocade-operation-device-management

### ISSUE THREAD

**Issue by RomainDusi** [brocade/ansible#86]
Hello,

I would like to do an FCPing to check if the WWN exists on a given context.
The module seems to be implemented on the API but i can't find it in the Ansible Collection.

Can you please redirect me if it exists or implement it ?

Thank you.

**Comment by daniel-chung-broadcom** [comment]
Hi, can you please clarify which API you are referring to? Also, if you can clarify the specific use case you are interested in, that would be very helpful. For example, are you looking to see if a particular wwn resides within a fabric? If so, there are find_ns_by*.yaml examples that you can reference.

**Comment by RomainDusi** [comment]
Hello,

That was exactly what i was searching for, thank you.
