### ISSUE TITLE
CSR generation playbook error

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#88]
Hello, I am getting the POST_resp_code": 400 error when running the "csr_gen_export.yml" playbook. Can you please look into this and let me know if I am doing anything wrong. Below is the playbook I am using and error details.

**Playbook:**
  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: xxxxxxx
      fos_password: xxxxxxxx
      https: True
    generate_inputs:
      certificate_entity: csr
      certificate_type: https
      country_name: US
      state_name: xxxxx
      locality_name: xxxxx
      organization_name: Dxxx xxxxxx xxxx
      unit_name: Dxxxx xxx xxx xxxx xxxx xxxxx
      domain_name: rxxxx.xxx.xxx.com

  tasks:
  - name: New CSR generation.
    brocade_security_security_certificate_generate:
      credential: "{{credential}}"
      vfid: -1
      generate_inputs: "{{generate_inputs}}

TASK [New CSR generation.] ***********************************************************************************************************************************************************************************
fatal: [rwfcr001]: FAILED! => {"POST_resp_code": 400, "POST_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "16715778", "error-module": "cal"}, "error-message": "Invalid input(s)", "error-path": "/security-certificate-generate/", "error-tag": "Operation-failed", "error-type": "application"}}}, "POST_resp_reason": "Bad Request", "POST_url": "https://********/rest/running/brocade-security/security-certificate-generate", "changed": false, "current_attributes": {}, "diff_attributes": {"certificate-entity": "csr", "certificate-type": "https", "country-name": "US", "domain-name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "locality-name": "Rxxxxxx", "organization-name": "Dxxx xxxxxx xxxx", "state-name": "xxxxx", "unit-name": "Dxxxx xxx xxx xxxx xxxx xxxxx"}, "msg": "POST failed", "new_attributes": {"certificate_entity": "csr", "certificate_type": "https", "country_name": "US", "domain_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "locality_name": "xxxxx", "organization_name": "Dxxx xxxxxx xxxx", "state_name": "Ixxxxx", "unit_name": "Dxxxx xxx xxx xxxx xxxx xxxxx"}, "patch_obj_str": "<security-certificate-generate><unit-name>Dxxxx xxx xxx xxxx xxxx xxxxx</unit-name><certificate-entity>csr</certificate-entity><state-name>xxxxx</state-name><locality-name>xxxxx</locality-name><certificate-type>https</certificate-type><domain-name>********</domain-name><organization-name>Dxxx xxxxxx xxxx</organization-name><country-name>US</country-name></security-certificate-generate>", "ssh_hostkeymust": true}

PLAY RECAP ***************************************************************************************************************************************************************************************************
rxxxxx                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
I ran my own testing and it generated ok for me. Will you be able to run the playbook with -vvvv to see if we could figure out the string that is being posted? I think the debug output will have the inputs in cleartext.

**Comment by autocoder10** [comment]
Here is the output from -vvv.. Just want to mention that we are on FOS 8.2.2d code. Below is the cli cmd we are using to generate the CSR.

**seccertmgmt generate -csr https**                        

ansible-playbook 2.9.19
  config file = /home/xxxxxx/ansible-brocade/ansible-9.0.0a/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /home/xxxxxx/ansible-brocade/ansible-9.0.0a/ansible.cfg as config file
host_list declined parsing /home/xxxxxx/ansible-brocade/ansible-9.0.0a/inventory as it did not pass its verify_file() method
script declined parsing /home/xxxxxx/ansible-brocade/ansible-9.0.0a/inventory as it did not pass its verify_file() method
auto declined parsing /home/xxxxxx/ansible-brocade/ansible-9.0.0a/inventory as it did not pass its verify_file() method
Parsed /home/xxxxxx/ansible-brocade/ansible-9.0.0a/inventory inventory source with ini plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: test_csr_gen_export.yml ****************************************************************************************************************************************************************************
1 plays in test_csr_gen_export.yml

PLAY [SANSwitches] *******************************************************************************************************************************************************************************************
META: ran handlers

TASK [New CSR generation.] ***********************************************************************************************************************************************************************************
task path: /home/xxxxxx/ansible-brocade/ansible-9.0.0a/test_csr_gen_export.yml:34
<rwfcr001> ESTABLISH LOCAL CONNECTION FOR USER: root
<rwfcr001> EXEC /bin/sh -c 'echo ~root && sleep 0'
<rwfcr001> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1625179368.97-12686-76457806099451 `" && echo ansible-tmp-1625179368.97-12686-76457806099451="` echo /root/.ansible/tmp/ansible-tmp-1625179368.97-12686-76457806099451 `" ) && sleep 0'
Using module file /home/xxxxxx/ansible-brocade/ansible-9.0.0a/library/brocade_security_security_certificate_generate.py
<rwfcr001> PUT /root/.ansible/tmp/ansible-local-12674huyr6g/tmpn4d898 TO /root/.ansible/tmp/ansible-tmp-1625179368.97-12686-76457806099451/AnsiballZ_brocade_security_security_certificate_generate.py
<rwfcr001> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1625179368.97-12686-76457806099451/ /root/.ansible/tmp/ansible-tmp-1625179368.97-12686-76457806099451/AnsiballZ_brocade_security_security_certificate_generate.py && sleep 0'
<rwfcr001> EXEC /bin/sh -c 'SSL_CERT_FILE=/home/xxxxxx/ansible-brocade/ansible/xxxxxxxxx /usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1625179368.97-12686-76457806099451/AnsiballZ_brocade_security_security_certificate_generate.py && sleep 0'
<rwfcr001> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1625179368.97-12686-76457806099451/ > /dev/null 2>&1 && sleep 0'
fatal: [rwfcr001]: FAILED! => {
    "POST_resp_code": 400, 
    "POST_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", 
            "error": {
                "error-app-tag": "Error", 
                "error-info": {
                    "error-code": "16715778", 
                    "error-module": "cal"
                }, 
                "error-message": "Invalid input(s)", 
                "error-path": "/security-certificate-generate/", 
                "error-tag": "Operation-failed", 
                "error-type": "application"
            }
        }
    }, 
    "POST_resp_reason": "Bad Request", 
    "POST_url": "https://********/rest/running/brocade-security/security-certificate-generate", 
    "changed": false, 
    "current_attributes": {}, 
    "diff_attributes": {
        "certificate-entity": "csr", 
        "certificate-type": "https", 
        "country-name": "US", 
        "domain-name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
        "locality-name": "xxxxxx", 
        "organization-name": "Dxxx xxxxxx xxxx", 
        "state-name": "xxxxxx", 
        "unit-name": "Dxxxx xxx xxx xxxx xxxx xxxxx"
    }, 
    "invocation": {
        "module_args": {
            "credential": {
                "fos_ip_addr": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "fos_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "fos_user_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "https": true
            }, 
            "generate_inputs": {
                "certificate_entity": "csr", 
                "certificate_type": "https", 
                "country_name": "US", 
                "domain_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "locality_name": "xxxxxx", 
                "organization_name": "Dxxx xxxxxx xxxx", 
                "state_name": "xxxxxx", 
                "unit_name": "Dxxxx xxx xxx xxxx xxxx xxxxx"
            }, 
            "throttle": null, 
            "timeout": null, 
            "vfid": -1
        }
    }, 
    "msg": "POST failed", 
    "new_attributes": {
        "certificate_entity": "csr", 
        "certificate_type": "https", 
        "country_name": "US", 
        "domain_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
        "locality_name": "xxxxxx", 
        "organization_name": "Dxxx xxxxxx xxxx", 
        "state_name": "xxxxxx", 
        "unit_name": "Dxxxx xxx xxx xxxx xxxx xxxxx"
    }, 
    "patch_obj_str": "<security-certificate-generate><unit-name>Dxxxx xxx xxx xxxx xxxx xxxxx</unit-name><certificate-entity>csr</certificate-entity><state-name>xxxxxx</state-name><locality-name>xxxxxx</locality-name><certificate-type>https</certificate-type><domain-name>********</domain-name><organization-name>Dxxx xxxxxx xxxx</organization-name><country-name>US</country-name></security-certificate-generate>", 
    "ssh_hostkeymust": true
}

PLAY RECAP ***************************************************************************************************************************************************************************************************
xxxxx                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
my patch_obj_str looks to contain the information whereas yours do not. do you not see any xml markups at all in your patch_obj_str before you hid the details?

    "patch_obj_str": "<security-certificate-generate>\n<locality-name>SJ</locality-name>\n<state-name>CA</state-name>\n<unit-name>BSN</unit-name>\n<country-name>US</country-name>\n<organization-name>Broadcom</organization-name>\n<certificate-type>https</certificate-type>\n<certificate-entity>csr</certificate-entity>\n<domain-name>xxx.xxx.xxx.xxx</domain-name>\n</security-certificate-generate>\n",

**Comment by autocoder10** [comment]
yes, I am seeing any xml markups at all in my patch_obj_str even before I hid the details....
Here is the stating part of my patch_obj_str without editing...

"patch_obj_str": "<security-certificate-generate><certificate-entity>csr</certificate-entity><state-name>Illinois</state-name><locality-name>RV</locality-name><certificate-type>https</certificate-type><domain-name>********</domain-name>......................</security-certificate-generate>"

**Comment by daniel-chung-broadcom** [comment]
I noticed that the elements in patch_obj_str are in a different order than what I am seeing, although your playbooks seem to have the content in the same order. I am wondering if we are using the same code base. Can you either try the latest on master or documentation_attribute_content_change? Just to match up the code base with my debugging?

**Comment by autocoder10** [comment]
I have tried latest from the master and still CSR generation module getting failed with the same error..

**Comment by daniel-chung-broadcom** [comment]
I am bit lost since the flow shouldn't be going through "post" path but just "patch" path. So, i am wondering where the post related error message is coming from.

can you please confirm that library/brocade_security_security_certificate_generate.py contains the following line at the end?

    singleton_helper(module, fos_ip_addr, fos_user_name, fos_password, https, ssh_hostkeymust, throttle, vfid, "brocade_security", "security_certificate_generate", generate_inputs, result, timeout)


if __name__ == '__main__':
    main()

**Comment by autocoder10** [comment]
Yes, I am seeing that line at the end.

 singleton_helper(module, fos_ip_addr, fos_user_name, fos_password, https, ssh_hostkeymust, throttle, vfid, "brocade_security", "security_certificate_generate", generate_inputs, result, timeout)


if __name__ == '__main__':
    main()

**Comment by daniel-chung-broadcom** [comment]
What is really puzzling is that this singleton_helper is not supposed to go through any 'post' code path. But in your debug output, there is a message indicating that the post failed. 

"msg": "POST failed",

When I do the following command under ansible/utils

grep msg * | grep POST

I only see 

brocade_zoning.py:                    result['msg'] = "HTTP POST failed"

I am not seeing any code that returns the message "POST failed" in the latest code within the result dictionary with "msg" as the index.

Can you please try the following

1) under your ansible/utils, grep for "POST failed" and see if you get a hit
2) look within the playbook, do you see any reference to 'collections'?
3) do you have ansible.cfg file under the directory where you are executing the playbook? If so, it is pointing to the same directory where you attempted #1?

Thanks.

**Comment by autocoder10** [comment]
I have tried with the .py modules from both master and documentation_attribute_content_change branch still seeing the same POST failed error

1. under your ansible/utils, grep for "POST failed" and see if you get a hit
[root@rxxxxx utils]# grep msg * | grep POST
brocade_zoning.py:                    result['msg'] = "HTTP POST failed"
[root@rxxxxx utils]# 

2. look within the playbook, do you see any reference to 'collections'?
No, I didn't use collections anywhere in my playbook.

[root@rxxxxx ansible-9.0.0a]# cat test_csr_gen_export.yml 
---
- hosts: SANSwitches
  gather_facts: False

  environment:
    SSL_CERT_FILE: xxxxx.pem
  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: xxxxxxx
      fos_password: xxxxxxx
      https: True
    generate_inputs:
      certificate_entity: csr
      certificate_type: https
      country_name: US
      state_name: xxxxx
      locality_name: xxxxx
      organization_name: Dxxx xxxxxx xxxx
      unit_name: Dxxxx xxx xxx xxxx xxxx xxxxx
      domain_name: rxxxx.xxx.xxx.com

  tasks:
  - name: New CSR generation.
    brocade_security_security_certificate_generate:
      credential: "{{credential}}"
      vfid: -1
      generate_inputs: "{{generate_inputs}}"

3. do you have ansible.cfg file under the directory where you are executing the playbook? If so, it is pointing to the same directory where you attempted SAN switches with 8.0.2b are not pining from Ansible #1?

Yes, I have "ansible.cfg" file in the Dir where I am executing the playbook and below the content it has.

[root@rxxxxx **ansible-9.0.0a**]# pwd
/home/sxxxxxx/ansible-brocade/ansible-9.0.0a

[root@rxxxxx **ansible-9.0.0a**]# cat ansible.cfg 
# config file for ansible -- https://ansible.com/
# ===============================================

# nearly all parameters can be overridden in ansible-playbook
# or with command line flags. ansible will read ANSIBLE_CONFIG,
# ansible.cfg in the current working directory, .ansible.cfg in
# the home directory or /etc/ansible/ansible.cfg, whichever it
# finds first

[defaults]

module_utils = /home/sxxxxxx/ansible-brocade/**ansible-9.0.0a**/utils
interpreter_python = /usr/bin/python3

[root@rxxxxx **ansible-9.0.0a**]# ll |grep test_csr_gen_export
-rw------- 1 sxxxxxx domusers  1289 Jul  1 11:46 test_csr_gen_export.yml

[root@rxxxxx **ansible-9.0.0a**]# ll |grep utils
drwx------ 2 sxxxxxx domusers  4096 Jul  6 12:02 utils


I also ran a test gather_facts.yml playbook on the same switch I am planning to generate a CSR and it is working without any issues.

**Comment by daniel-chung-broadcom** [comment]
The only diff that I see in my playbook was environment tag. So, I added that and replaced all the variables with the xxx to mimic the naming length and spacing. I am not having any trouble in my env. Can I assume that you do not have any other copy of the brocade/ansible cloned in your env? 

dc400196@iaas-l-2206-611:~/ansible$ ansible-playbook -i san-inventory test.yml -vvvv
ansible-playbook 2.9.0
  config file = /home/dc400196/ansible/ansible.cfg
  configured module search path = ['/home/dc400196/ansible/library', '/home/dc400196/dell/ansible-fos-command/library']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.2 (default, Apr 16 2020, 17:47:17) [GCC 5.4.0 20160609]
Using /home/dc400196/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/dc400196/ansible/san-inventory as it did not pass its verify_file() method
script declined parsing /home/dc400196/ansible/san-inventory as it did not pass its verify_file() method
auto declined parsing /home/dc400196/ansible/san-inventory as it did not pass its verify_file() method
Parsed /home/dc400196/ansible/san-inventory inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.5/dist-packages/ansible/plugins/callback/default.py

PLAYBOOK: test.yml *********************************************************************************
Positional arguments: test.yml
timeout: 10
connection: smart
inventory: ('/home/dc400196/ansible/san-inventory',)
verbosity: 4
forks: 5
tags: ('all',)
become_method: sudo
1 plays in test.yml

PLAY [san_eng_zone_seed_san_a] *********************************************************************
META: ran handlers

TASK [CSR generation. Existing CSR is not compared. This task will always change.] *****************
task path: /home/dc400196/ansible/test.yml:32
[WARNING]: could not parse environment value, skipping: ['SSL_CERT_FILE:mine.pem']

<san_eng_zone_seed_san_a> ESTABLISH LOCAL CONNECTION FOR USER: dc400196
<san_eng_zone_seed_san_a> EXEC /bin/sh -c 'echo ~dc400196 && sleep 0'
<san_eng_zone_seed_san_a> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dc400196/.ansible/tmp/ansible-tmp-1625591728.4954953-89143514039868 `" && echo ansible-tmp-1625591728.4954953-89143514039868="` echo /home/dc400196/.ansible/tmp/ansible-tmp-1625591728.4954953-89143514039868 `" ) && sleep 0'
<san_eng_zone_seed_san_a> Attempting python interpreter discovery
<san_eng_zone_seed_san_a> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<san_eng_zone_seed_san_a> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/dc400196/ansible/library/brocade_security_security_certificate_generate.py
<san_eng_zone_seed_san_a> PUT /home/dc400196/.ansible/tmp/ansible-local-1583095a3siabz/tmpirl_desv TO /home/dc400196/.ansible/tmp/ansible-tmp-1625591728.4954953-89143514039868/AnsiballZ_brocade_security_security_certificate_generate.py
<san_eng_zone_seed_san_a> EXEC /bin/sh -c 'chmod u+x /home/dc400196/.ansible/tmp/ansible-tmp-1625591728.4954953-89143514039868/ /home/dc400196/.ansible/tmp/ansible-tmp-1625591728.4954953-89143514039868/AnsiballZ_brocade_security_security_certificate_generate.py && sleep 0'
<san_eng_zone_seed_san_a> EXEC /bin/sh -c '/usr/bin/python3 /home/dc400196/.ansible/tmp/ansible-tmp-1625591728.4954953-89143514039868/AnsiballZ_brocade_security_security_certificate_generate.py && sleep 0'
<san_eng_zone_seed_san_a> EXEC /bin/sh -c 'rm -f -r /home/dc400196/.ansible/tmp/ansible-tmp-1625591728.4954953-89143514039868/ > /dev/null 2>&1 && sleep 0'
changed: [san_eng_zone_seed_san_a] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": true,
    "current_attributes": {},
    "diff_attributes": {
        "certificate-entity": "csr",
        "certificate-type": "https",
        "country-name": "US",
        "domain-name": "rxxxxx.xxx.xxx.com",
        "locality-name": "xxxxx",
        "organization-name": "Dxxx xxxxxx xxxx",
        "state-name": "xxxxx",
        "unit-name": "Dxxxx xxx xxx xxxx xxxx xxxxx"
    },
    "invocation": {
        "module_args": {
            "credential": {
                "fos_ip_addr": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "fos_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "fos_user_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "https": false
            },
            "generate_inputs": {
                "certificate_entity": "csr",
                "certificate_type": "https",
                "country_name": "US",
                "domain_name": "rxxxxx.xxx.xxx.com",
                "locality_name": "xxxxx",
                "organization_name": "Dxxx xxxxxx xxxx",
                "state_name": "xxxxx",
                "unit_name": "Dxxxx xxx xxx xxxx xxxx xxxxx"
            },
            "throttle": null,
            "timeout": null,
            "vfid": -1
        }
    },
    "new_attributes": {
        "certificate_entity": "csr",
        "certificate_type": "https",
        "country_name": "US",
        "domain_name": "rxxxxx.xxx.xxx.com",
        "locality_name": "xxxxx",
        "organization_name": "Dxxx xxxxxx xxxx",
        "state_name": "xxxxx",
        "unit_name": "Dxxxx xxx xxx xxxx xxxx xxxxx"
    },
    "patch_obj_str": "<security-certificate-generate>\n<locality-name>xxxxx</locality-name>\n<certificate-entity>csr</certificate-entity>\n<state-name>xxxxx</state-name>\n<certificate-type>https</certificate-type>\n<organization-name>Dxxx xxxxxx xxxx</organization-name>\n<country-name>US</country-name>\n<unit-name>Dxxxx xxx xxx xxxx xxxx xxxxx</unit-name>\n<domain-name>rxxxxx.xxx.xxx.com</domain-name>\n</security-certificate-generate>\n",
    "ssh_hostkeymust": true
}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************
san_eng_zone_seed_san_a    : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
I just pushed some debug print statements on 'debugging' branch. Do you mind setting your env to 'debugging' and run the script with -vvvv option and see what it prints? I am hoping that it will give us some idea as to the flow of the code. In my execution, I see

dc400196@iaas-l-2206-611:~/ansible$ ansible-playbook -i san-inventory test.yml -vvvv
..
..
..

    "patch_obj_str": "<security-certificate-generate>\n<certificate-entity>csr</certificate-entity>\n<locality-name>xxxxx</locality-name>\n<state-name>xxxxx</state-name>\n<organization-name>Dxxx xxxxxx xxxx</organization-name>\n<country-name>US</country-name>\n<unit-name>Dxxxx xxx xxx xxxx xxxx xxxxx</unit-name>\n<domain-name>rxxxxx.xxx.xxx.com</domain-name>\n<certificate-type>https</certificate-type>\n</security-certificate-generate>\n",
    "ssh_hostkeymust": true,
    "xdebug1": "here",
    "xdebug2": "here",
    "xdebug3": "here",
    "xdebug5": "here"

**Comment by autocoder10** [comment]
Yes, I don't have any other clones in my dir. Here is the playbook output for "brocade_objects.py" from debugging branch. I see I only got three "xdebug",

[root@rxxxxxx ansible-9.0.0a]# ansible-playbook test_csr_gen_export.yml -i inventory_cert -vvv
ansible-playbook 2.9.19
  config file = /home/xxxxxx/ansible-brocade/ansible-9.0.0a/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /home/xxxxxx/ansible-brocade/ansible-9.0.0a/ansible.cfg as config file
host_list declined parsing /home/xxxxxx/ansible-brocade/ansible-9.0.0a/inventory_cert as it did not pass its verify_file() method
script declined parsing /home/xxxxxx/ansible-brocade/ansible-9.0.0a/inventory_cert as it did not pass its verify_file() method
auto declined parsing /home/xxxxxx/ansible-brocade/ansible-9.0.0a/inventory_cert as it did not pass its verify_file() method
Parsed /home/xxxxxx/ansible-brocade/ansible-9.0.0a/inventory_cert inventory source with ini plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: test_csr_gen_export.yml ****************************************************************************************************************************************************************************
1 plays in test_csr_gen_export.yml

PLAY [SANSwitches] *******************************************************************************************************************************************************************************************
META: ran handlers

TASK [New CSR generation.] ***********************************************************************************************************************************************************************************
task path: /home/xxxxxx/ansible-brocade/ansible-9.0.0a/test_csr_gen_export.yml:34
<switch1> ESTABLISH LOCAL CONNECTION FOR USER: root
<switch1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<switch1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1625595439.31-4201-139875996967260 `" && echo ansible-tmp-1625595439.31-4201-139875996967260="` echo /root/.ansible/tmp/ansible-tmp-1625595439.31-4201-139875996967260 `" ) && sleep 0'
Using module file /home/xxxxxx/ansible-brocade/ansible-9.0.0a/library/brocade_security_security_certificate_generate.py
<switch1> PUT /root/.ansible/tmp/ansible-local-4189s5jCcW/tmp2xfZnV TO /root/.ansible/tmp/ansible-tmp-1625595439.31-4201-139875996967260/AnsiballZ_brocade_security_security_certificate_generate.py
<switch1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1625595439.31-4201-139875996967260/ /root/.ansible/tmp/ansible-tmp-1625595439.31-4201-139875996967260/AnsiballZ_brocade_security_security_certificate_generate.py && sleep 0'
<switch1> EXEC /bin/sh -c 'SSL_CERT_FILE=/home/xxxxxx/ansible-brocade/ansible/xxxxxx.pem /usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1625595439.31-4201-139875996967260/AnsiballZ_brocade_security_security_certificate_generate.py && sleep 0'
<switch1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1625595439.31-4201-139875996967260/ > /dev/null 2>&1 && sleep 0'
fatal: [switch1]: FAILED! => {
    "POST_resp_code": 400, 
    "POST_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", 
            "error": {
                "error-app-tag": "Error", 
                "error-info": {
                    "error-code": "16715778", 
                    "error-module": "cal"
                }, 
                "error-message": "Invalid input(s)", 
                "error-path": "/security-certificate-generate/", 
                "error-tag": "Operation-failed", 
                "error-type": "application"
            }
        }
    }, 
    "POST_resp_reason": "Bad Request", 
    "POST_url": "https://********/rest/running/brocade-security/security-certificate-generate", 
    "changed": false, 
    "current_attributes": {}, 
    "diff_attributes": {
        "certificate-entity": "csr", 
        "certificate-type": "https", 
        "country-name": "US", 
        "domain-name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
        "locality-name": "xxxxxx", 
        "organization-name": "Dxxx xxxxxx xxxx", 
        "state-name": "xxxxxx", 
        "unit-name": "Dxxxx xxx xxx xxxx xxxx xxxxx"
    }, 
    "invocation": {
        "module_args": {
            "credential": {
                "fos_ip_addr": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "fos_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "fos_user_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "https": true
            }, 
            "generate_inputs": {
                "certificate_entity": "csr", 
                "certificate_type": "https", 
                "country_name": "US", 
                "domain_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "locality_name": "xxxxxx", 
                "organization_name": "Dxxx xxxxxx xxxx", 
                "state_name": "xxxxxx", 
                "unit_name": "Dxxxx xxx xxx xxxx xxxx xxxxx"
            }, 
            "throttle": null, 
            "timeout": null, 
            "vfid": -1
        }
    }, 
    "msg": "POST failed", 
    "new_attributes": {
        "certificate_entity": "csr", 
        "certificate_type": "https", 
        "country_name": "US", 
        "domain_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
        "locality_name": "xxxxxx", 
        "organization_name": "Dxxx xxxxxx xxxx", 
        "state_name": "xxxxxx", 
        "unit_name": "Dxxxx xxx xxx xxxx xxxx xxxxx"
    }, 
    "patch_obj_str": "<security-certificate-generate>\n<unit-name>Dxxxx xxx xxx xxxx xxxx xxxxx</unit-name>\n<certificate-entity>csr</certificate-entity>\n<state-name>xxxxxx</state-name>\n<locality-name>xxxxxx</locality-name>\n<certificate-type>https</certificate-type>\n<domain-name>********</domain-name>\n<organization-name>Dxxx xxxxxx xxxx</organization-name>\n<country-name>US</country-name>\n</security-certificate-generate>\n", 
    "ssh_hostkeymust": true, 
    "xdebug1": "here", 
    "xdebug2": "here", 
    "xdebug3": "here"
}

PLAY RECAP ***************************************************************************************************************************************************************************************************
switch1                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by daniel-chung-broadcom** [comment]
I was mistaken about the code path. it turns out that post is exactly what is being used. Here is the code path that is taken within singleton_patch(). I think your execution is not seeing the last one because I believe the url_post must be existing out instead of returning.

I am tyring to figure out if anything has changed between 8.2.2d and latest FOS release in this area. I verified must of the code against 8.2.1 but I think cert generation modules were written later and not sure if they were tested against 8.2.x code basis.

    if module_name == "brocade_security" and obj_name == "security_certificate_generate":
        return url_post(fos_ip_addr, is_https, auth, vfid, result,
                        full_url, xml_str, timeout)

**Comment by autocoder10** [comment]
ok Sure.. Can you test the CSR generation module with FOS 8.2.2d code and let me know.

**Comment by autocoder10** [comment]
@daniel-chung-broadcom Any update on testing the CSR generation module with FOS 8.2.2d code from your end..

**Comment by daniel-chung-broadcom** [comment]
I found that it is a known issue on fos 8.2.2d that has been addressed in 8.2.3a. I am following up to see if there are any known workarounds. I am not aware of any workarounds with 8.2.2d release at the moment.

**Comment by autocoder10** [comment]
Thanks for the update... Please let me know if you find any workaround. Really appreciate your support.

**Comment by autocoder10** [comment]
Any update on the workaround for CSR generation module with FOS 8.2.2d?

**Comment by daniel-chung-broadcom** [comment]
I am sorry but it looks like there are no known workarounds on 8.2.2d.

**Comment by autocoder10** [comment]
ok.. Will the certificate modules work for FOS 9.x.x code levels???

**Comment by daniel-chung-broadcom** [comment]
Yes. I believe I was testing with 9.0.0 during our correspondence.

**Comment by daniel-chung-broadcom** [comment]
If you have a specific build in mind, let me know.

**Comment by autocoder10** [comment]
> Yes. I believe I was testing with 9.0.0 during our correspondence.

Ok.. Thanks for the update.

**Comment by autocoder10** [comment]
> If you have a specific build in mind, let me know.

As of now we are planning to go to FOS 9.0.1b. Can you please review the Certificate modules and let me know if those work with FOS 9.0.1b.

**Comment by autocoder10** [comment]
> I am sorry but it looks like there are no known workarounds on 8.2.2d.

Is there any defect number that we can reference for this known issue.

**Comment by daniel-chung-broadcom** [comment]
the defect is disclosed as FOS-828373 in RN for 8.2.3a

**Comment by autocoder10** [comment]
> the defect is disclosed as FOS-828373 in RN for 8.2.3a

Thanks again for the info

**Comment by daniel-chung-broadcom** [comment]
re-ran the failing playbook with 9.0.1b and csr/https was generated. verified with facts playbook. fyi.

**Comment by autocoder10** [comment]
> re-ran the failing playbook with 9.0.1b and csr/https was generated. verified with facts playbook. fyi.

Thanks for testing and the update. Will test from my end and let you know if I encounter any issues.

**Comment by daniel-chung-broadcom** [comment]
closing based on the last comment. Please reopen or open another issue if additional problems or comments around this area.
