### ISSUE TITLE
LDAP/AD config module

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#90]
Hello, Is there any module I can use to configure and view Active Directory on the switch??

Example CLI command:
aaaconfig --add [server] -conf ldap -p [port] -d [domain]

aaaconfig --show

**Comment by daniel-chung-broadcom** [comment]
I don't have any named modules but I tested template object modules on ldap configuration earlier. Here is how the task section of the playbook looks like

  tasks:

  - name: change
    brocade_list_obj:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_security"
      list_name: "ldap_server"
      entries:
        - server: "10.10.10.10"
          port: 389
          domain: "local"
          timeout: 3
          tls_mode: "starttls"

  - name: change
    brocade_singleton_obj:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_security"
      obj_name: "auth_spec"
      attributes:
        authentication_mode: "ldap;local"

template_facts_all.yaml contains display of ldap server information.

Please check these out and let me know if these are what you are looking for or any questions.

**Comment by autocoder10** [comment]
Sure, Daniel. I will try those modules and will update.

**Comment by autocoder10** [comment]
I am configuring the LDAP on a brand new switch which currently doesn't have any LDAP config on it.

DS_6630B:FID128:admin> aaaconfig --show
RADIUS CONFIGURATIONS
=====================
RADIUS configuration does not exist.

LDAP CONFIGURATIONS
===================
LDAP configuration does not exist.

TACACS+ CONFIGURATIONS
=====================
TACACS+ configuration does not exist.

Primary AAA Service: Switch database
Secondary AAA Service: None
Log Primary Authentication Status: Yes

I am using the exact same task you mentioned and seeing the below error.

**tasks:**

- name: change
  brocade_list_obj:
    credential: "{{credential}}"
    vfid: -1
    module_name: "brocade_security"
    list_name: "ldap_server"
    entries:
    - server: "10.10.10.10"
    port: 389
    domain: "local"
    timeout: 3

**Error:**
"msg": "Unsupported parameters for (brocade_list_obj) module: domain, port Supported parameters include: all_entries, credential, entries, list_name, module_name, throttle, timeout, vfid",

Then, If I update the task with indentation now seeing the below error.

**tasks:**

- name: change
  brocade_list_obj:
    credential: "{{credential}}"
    vfid: -1
    module_name: "brocade_security"
    list_name: "ldap_server"
    entries:
    - server: "10.10.10.10"
    - port: 389
    - domain: "local"
    - timeout: 3
    - 
**Error:**
fatal: [10.15.16.17]: FAILED! => {"GET_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "16717059", "error-module": "cal"}, "**error-message": "LDAP configuration does not exist."**, "error-path": "/ldap-server/", "error-tag": "Operation-failed", "error-type": "application"}}}, "POST_resp_code": 400, "POST_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": [{"error-app-tag": "Error", "error-info": {"error-code": "-2", "error-module": "security"}, "error-message": "Unknown IP address for LDAP server", "error-path": "/ldap-server/server/10.10.10.10/", "error-tag": "Operation-failed", "error-type": "protocol"}, {"error-app-tag": "Error", "error-info": {"error-code": "16717056", "error-module": "cal"}, "error-message": "missing SERVER property", "error-path": "/ldap-server/", "error-tag": "Operation-failed", "error-type": "application"}, {"error-app-tag": "Error", "error-info": {"error-code": "16717056", "error-module": "cal"}, "error-message": "missing SERVER property", "error-path": "/ldap-server/", "error-tag": "Operation-failed", "error-type": "application"}, {"error-app-tag": "Error", "error-info": {"error-code": "16717056", "error-module": "cal"}, "error-message": "missing SERVER property", "error-path": "/ldap-server/", "error-tag": "Operation-failed", "error-type": "application"}]}}, "POST_resp_reason": "Bad Request", "POST_url": "http://********/rest/running/brocade-security/ldap-server", "add_entries": [{"server": "10.10.10.10"}, {"port": 389}, {"domain": "local"}, {"timeout": 3}], "add_retcode": 0, "all_entries_default": null, "changed": false, "current_entries": [], "delete_entries": [], "delete_retcode": 0, "diff_entries": [], "diff_retcode": 0, "msg": "POST failed", "post_str": "<ldap-server><server>10.10.10.10</server></ldap-server><ldap-server><port>389</port></ldap-server><ldap-server><domain>local</domain></ldap-server><ldap-server><timeout>3</timeout></ldap-server>", "response": {"Response": {"ldap-server": []}}}

**Comment by autocoder10** [comment]
Sry-- under entries in the task those are all "-".

**Comment by daniel-chung-broadcom** [comment]
unfortunately, I am not having issues that you are.

here is before:

Tyr1-ASCG-Demo:FID128:admin> aaaconfig --show
RADIUS CONFIGURATIONS
=====================
RADIUS configuration does not exist.

LDAP CONFIGURATIONS
===================
LDAP configuration does not exist.

TACACS+ CONFIGURATIONS
=====================
TACACS+ configuration does not exist.

Primary AAA Service: Switch database
Secondary AAA Service: None
Log Primary Authentication Status: Yes

and after on FOS side:

Tyr1-ASCG-Demo:FID128:admin> aaaconfig --show
RADIUS CONFIGURATIONS
=====================
RADIUS configuration does not exist.

LDAP CONFIGURATIONS
===================

Position                 : 1
Server                   : 10.10.10.10
Port                     : 389
Domain                   : local
Timeout(s)               : 3
LDAP TLS Mode            : STARTTLS

TACACS+ CONFIGURATIONS
=====================
TACACS+ configuration does not exist.

Primary AAA Service: Switch database
Secondary AAA Service: None
Log Primary Authentication Status: Yes

Here is what my playbook looks like

  - name: change
    brocade_list_obj:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_security"
      list_name: "ldap_server"
      entries:
        - server: "10.10.10.10"
          port: 389
          domain: "local"
          timeout: 3
          tls_mode: "starttls"


Do you want to shoot me the output from ansible-playbook with -vvvv option added? It should give some debug information that might shed some light on what is going on.

**Comment by autocoder10** [comment]
Just want to mention the new switches are on FOS v8.2.1c.  Here is the error with -vvv debug option.

fatal: [10.15.16.17]: FAILED! => {
    "GET_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf",
            "error": {
                "error-app-tag": "Error",
                "error-info": {
                    "error-code": "16717059",
                    "error-module": "cal"
                },
                "error-message": "LDAP configuration does not exist.",
                "error-path": "/ldap-server/",
                "error-tag": "Operation-failed",
                "error-type": "application"
            }
        }
    },
    "POST_resp_code": 400,
    "POST_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf",
            "error": [
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "-2",
                        "error-module": "security"
                    },
                    "error-message": "Unknown IP address for LDAP server",
                    "error-path": "/ldap-server/server/10.10.10.10/",
                    "error-tag": "Operation-failed",
                    "error-type": "protocol"
                },
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "16717056",
                        "error-module": "cal"
                    },
                    "error-message": "missing SERVER property",
                    "error-path": "/ldap-server/",
                    "error-tag": "Operation-failed",
                    "error-type": "application"
                },
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "16717056",
                        "error-module": "cal"
                    },
                    "error-message": "missing SERVER property",
                    "error-path": "/ldap-server/",
                    "error-tag": "Operation-failed",
                    "error-type": "application"
                },
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "16717056",
                        "error-module": "cal"
                    },
                    "error-message": "missing SERVER property",
                    "error-path": "/ldap-server/",
                    "error-tag": "Operation-failed",
                    "error-type": "application"
                }
            ]
        }
    },
    "POST_resp_reason": "Bad Request",
    "POST_url": "http://********/rest/running/brocade-security/ldap-server",
    "add_entries": [
        {
            "server": "10.10.10.10"
        },
        {
            "port": 389
        },
        {
            "domain": "local"
        },
        {
            "timeout": 3
        }
    ],
    "add_retcode": 0,
    "all_entries_default": null,
    "changed": false,
    "current_entries": [],
    "delete_entries": [],
    "delete_retcode": 0,
    "diff_entries": [],
    "diff_retcode": 0,
    "invocation": {
        "module_args": {
            "all_entries": null,
            "credential": {
                "fos_ip_addr": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "fos_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "fos_user_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "https": false
            },
            "entries": [
                {
                    "server": "10.10.10.10"
                },
                {
                    "port": 389
                },
                {
                    "domain": "local"
                },
                {
                    "timeout": 3
                }
            ],
            "list_name": "ldap_server",
            "module_name": "brocade_security",
            "throttle": null,
            "timeout": null,
            "vfid": -1
        }
    },
    "msg": "POST failed",
    "post_str": "<ldap-server><server>10.10.10.10</server></ldap-server><ldap-server><port>389</port></ldap-server><ldap-server><domain>local</domain></ldap-server><ldap-server><timeout>3</timeout></ldap-server>",
    "response": {
        "Response": {
            "ldap-server": []
        }
    }
}

**Comment by daniel-chung-broadcom** [comment]
I have no idea how your post string shows up like

"post_str": "10.10.10.10389local3",

Is there any way you can send me a copy of your playbook?

**Comment by autocoder10** [comment]
This is the task I'm using in the playbook.

tasks:

name: change
brocade_list_obj:
credential: "{{credential}}"
vfid: -1
module_name: "brocade_security"
list_name: "ldap_server"
entries:
- server: "10.10.10.10"
- port: 389
- domain: "local"
- timeout: 3

**Comment by daniel-chung-broadcom** [comment]
unfortunately, the copy and paste into the github issue seems to mess up the indentation. Here is what I am using.

<two spaces>- name: change
<four spaces>brocade_list_obj:
<six spaces>credential: "{{credential}}"
<six spaces>vfid: -1
<six spaces>module_name: "brocade_security"
<six spaces>list_name: "ldap_server"
<xix spaces>entries:
<eight spaces>- server: "10.10.10.10"
<10 spaces>port: 389
<10 spaces>domain: "local"
<10 spaces>timeout: 3
<10 spaces>tls_mode: "starttls"

that should produce the poststr as below:

    "post_str": "<ldap-server>\n<server>10.10.10.10</server>\n<tls-mode>starttls</tls-mode>\n<timeout>3</timeout>\n<domain>local</domain>\n<port>389</port>\n</ldap-server>\n",

In your playbook, it looks like you have "-" in front of server, port, domain, and timeout. That would be invalid. "-" indicates the beginning of an array. "entrys" is the name of the array. And the array contains one entry that contains 5 attributes: server, port, domain, timeout, and tls_mode. In your example, you are providing 4 entries each with one attribute.

Anyway, I add ldap_server.yml to documentation_attribute_content_change branch for indentation reference. Please take a look to see if your issue is an indentation issue in your playbook.

**Comment by autocoder10** [comment]
Yea, it's working now. I see indentation it is the problem as suspected. Thanks Daniel for the help.

I need few more modules that I'm looking for.

1. Configure password policies. 
Example CLI cmd: 
passwdcfg --set -minlength 6  -lowercase 1 -uppercase 0  -digits 1 -punctuation 1 -history 10 -minpasswordage 1 -maxpasswordage 30 -warning 10 -lockoutthreshold 3 -lockoutduration 30 –repeat 1  -sequence 1
passwdcfg --setuser cmcne -maxpasswordage 365

2. Configure account auto log out. 
Example CLI cmd:  passwdcfg -enableadminlockout

3. Enable dynamic port licensing.
Example CLI cmd: licenseport --reserve 0-23

**Comment by daniel-chung-broadcom** [comment]
I noticed earlier that you had questions in regards to passwdcfg - at least in the email that I received and I was following up to get the answers for you. But it is gone now. Can I assume that you were able to resolve them on your own?

As for licenseport, the RW support is in 9.x. In your 8.2.x release, I believe only RO is supported.

https://github.com/brocade/yang/blob/master/9.0.1/9.0.1b/brocade-interface.yang

     leaf pod-license-state {
	   if-feature fibrechannel:fibrechannel_standalone_switch_platform;
        type enumeration {
          enum "reserved" {
            description
            "
            The port is reserved under POD license.
            ";
          }
          enum "released" {
            description
            "
            The port is not reserved under POD license.
            ";
          }
        }
        description
          "
          POD license status of the logical port.
          ";
     }

for portname.yml, I don't believe the name field will take range according to the description.

      leaf name {
        type string {
          /* pattern with 12 slots and 1024 ports separated by a slash */
          pattern "([0-9]|1[0-9])/(10[0-2][0-9]|[1-9][0-9][0-9]|[1-9][0-9]|" + 
                  "[0-9])";
        }
        description
          "
          The name of the interface. The slot and port number of the specified 
          port in the format slot/port.
          ";
      }

**Comment by autocoder10** [comment]
Yea I am able to get the pwdcfg stuff using brocade_security module. Thanks for the info related to the port license and portname stuff. 

I believe we can close this issue for now.

**Comment by daniel-chung-broadcom** [comment]
Thanks for the update. Closing.
