### ISSUE TITLE
Getting error when trying to add new user acc.

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#92]
I am getting below error when trying to add new local user acc using  brocade_security_user_config module. I am using the exact same format mentioned in the switch_initial_config.yml playbook from line 363.

playbook task:
  - name: add new account
    brocade_security_user_config:
      credential: "{{credential}}"
      vfid: -1
      user_configs:
        - name: "test"
          password: "EadC12dF,s"
          virtual_fabric_role_id_list:
            role_id:
              -  "admin=1-128"
          chassis_access_role: "admin"

NOTE: As you are aware indentation is messing up in GitHub. So just want to mention that it is same as the one mentioned in the switch_initial_config.yml playbook from line 363.

TASK [add new account] *********************************************************
fatal: [10.15.16.17]: FAILED! => {
    "POST_resp_code": 400,
    "POST_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf",
            "error": {
                "error-app-tag": "Error",
                "error-info": {
                    "error-code": "16715778",
                    "error-module": "cal"
                },
                "error-message": "Invalid or extra parameters in input request",
                "error-path": "/user-config/name/test/",
                "error-tag": "Operation-failed",
                "error-type": "application"
            }
        }
    },
    "POST_resp_reason": "Bad Request",
    "POST_url": "http://********/rest/running/brocade-security/user-config",
    "add_entries": [
        {
            "chassis-access-role": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "name": "test",
            "password": "EadC12dF,s",
            "virtual-fabric-role-id-list": {
                "role-id": [
                    "********=1-128"
                ]
            }
        }
    ],
    "add_retcode": 0,
    "changed": false,
    "current_entries": [
        {
            "access_end_time": null,
            "access_start_time": null,
            "account_description": "root",
            "account_enabled": false,
            "account_locked": false,
            "name": "root",
            "password_change_enforced": false,
            "role": "root"
        },
        {
            "access_end_time": null,
            "access_start_time": null,
            "account_description": "Administrator",
            "account_enabled": true,
            "account_locked": false,
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "password_change_enforced": false,
            "role": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        },
        {
            "access_end_time": null,
            "access_start_time": null,
            "account_description": "User",
            "account_enabled": true,
            "account_locked": false,
            "name": "user",
            "password_change_enforced": false,
            "role": "user"
        }
    ],
    "delete_entries": [
        {
            "name": "root"
        },
        {
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        },
        {
            "name": "user"
        }
    ],
    "delete_retcode": 0,
    "diff_entries": [],
    "diff_retcode": 0,
    "invocation": {
        "module_args": {
            "credential": {
                "fos_ip_addr": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "fos_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "fos_user_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "https": false
            },
            "delete_user_configs": null,
            "throttle": null,
            "timeout": null,
            "user_configs": [
                {
                    "chassis_access_role": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "name": "test",
                    "password": "EadC12dF,s",
                    "virtual_fabric_role_id_list": {
                        "role_id": [
                            "********=1-128"
                        ]
                    }
                }
            ],
            "vfid": -1
        }
    },
    "msg": "POST failed",
    "name": "key identified",
    "post_str": "<user-config><name>test</name><password>EadC12dF,s</password><virtual-fabric-role-id-list><role-id>********=1-128</role-id></virtual-fabric-role-id-list><chassis-access-role>********</chassis-access-role></user-config>",
    "response": {
        "Response": {
            "user-config": [
                {
                    "access_end_time": null,
                    "access_start_time": null,
                    "account_description": "root",
                    "account_enabled": false,
                    "account_locked": false,
                    "name": "root",
                    "password_change_enforced": false,
                    "role": "root"
                },
                {
                    "access_end_time": null,
                    "access_start_time": null,
                    "account_description": "Administrator",
                    "account_enabled": true,
                    "account_locked": false,
                    "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "password_change_enforced": false,
                    "role": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                },
                {
                    "access_end_time": null,
                    "access_start_time": null,
                    "account_description": "User",
                    "account_enabled": true,
                    "account_locked": false,
                    "name": "user",
                    "password_change_enforced": false,
                    "role": "user"
                }
            ]
        }
    }
}

PLAY RECAP *********************************************************************
10.15.16.17              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Need to add the new acc with the below details similar to the CLI cmd..
From CLI
# userconfig --add test -r admin -d test -p EadC12dF,s -a 0-255

# userconfig --show test
Account name: test
Description: test
Enabled: Yes
Password Last Change Date: Tue Sep 14 2021 (UTC)
Password Expiration Date: Fri Oct 29 2021 (UTC)
Locked: No
Role: admin
AD membership: 0-255
Home AD: 0
Day Time Access: N/A

**Comment by mgoetze5** [comment]
It looks like the comma in the password isn't being escaped properly. As a workaround, try using a password without a comma.

**Comment by daniel-chung-broadcom** [comment]
The issue is known and will be addressed in a future FOS release. The workaround is as suggested by mgoetze5: avoid using , in the password.
