### ISSUE TITLE
brocade_operation_firmwaredownload: 

### ISSUE THREAD

**Issue by blakeysmith** [brocade/ansible#97]
When running a task with module brocade_operation_firmwaredownload, I get an "Invalid REST URI" error. 

fatal: [ZUSNWN5A]: FAILED! => {
    "GET_url": "https://********/rest/running/brocade-fibrechannel-switch/fibrechannel-switch",
    "POST_resp_code": 400,
    "POST_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf",
            "error": {
                "error-app-tag": "Error",
                "error-info": {
                    "error-code": "5",
                    "error-module": "rest"
                },
                "error-message": "Invalid REST URI",
                "error-tag": "unknown-element",
                "error-type": "application"
            }
        }

Task:

  - name: initiate firmwaredownload
    brocade_operation_firmwaredownload:
      credential: "{{credential}}"
      vfid: -1
      firmwaredownload: "{{firmwaredownload}}"
    register: result

I do have success in reading and setting data in the brocade-fibrechannel-switch/fibrechannel-switch tree with brocade_list_obj_facts & brocade_fibrechannel_switch.

Environment:

ansible 2.9.6
  config file = /root/playbooks/ansible.cfg
  configured module search path = ['/ansible/library', '/ansible-fos-command']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]

FOS Versions:
v8.2.1e & v8.2.2d

**Comment by prabhu-broadcom** [comment]
Hi,
The minimum FOS version for ansible module firmwaredownload is v9.0.0. There is no support for v8.2x releases. 

Thanks,

**Comment by blakeysmith** [comment]
Thanks!!
