### ISSUE TITLE
Connect using ssh key

### ISSUE THREAD

**Issue by RomainDusi** [brocade/ansible#99]
Hello,

I'm trying to get rid of passwords in my playbooks, so i activated the ssh key connection between my work server and the switches.
It is working as intended in a shell but i can't get it to work using "credentials" in ansible.

Can you please explain me how to do so if it is possible or implement this functionality otherwise ?

Thank you.

Example : 

_credential: 
  fos_ip_addr: SwticthIP
  fos_user_name: admin
  ssh_key: Path_To_SSH_KEY
  https: False_

**Comment by prabhu-broadcom** [comment]
Hi,
There is no support for ssh key based authentication in ansible since the backend APIs don't support that. Please use certificate based HTTPS authentication instead. 

Thanks,
